### PR TITLE
Removed unnecessary mock counter and switch during constructors mocking

### LINKED ISSUE #1878: Remove `switch` and `mockClassCounter` in `mockConstruction` in simple `mockConstruction` cases
**Description**

Unneeded sophistication of mockConstruction:
`switch` statement in `mockConstruction` definition and `mockClassCounter` can be avoided here.

**To Reproduce**

1. Install one of the latest plugin builds from main into IntelliJ Idea 2022.2.*
2. Open/clone "utbot" project
3. Use plugin to generate tests for `org.utbot.examples.mock.provider.impl.ProviderImpl#provideObject`
4. Open the generated test 

**Expected behavior**

`switch` statement in `mockConstruction` definition and `mockClassCounter` can be avoided here.
The constructed Object will be the same for all instantiations.

**Actual behavior**

There is unnecessary `switch` statement and `mockClassCounter` used in `mockConstruction.
It is confusing for a user.

**Visual proofs (screenshots, logs, images)**

~~~java
    ///region SYMBOLIC EXECUTION: SUCCESSFUL EXECUTIONS for method provideObject()

    /**
     * @utbot.classUnderTest {@link ProviderImpl}
     * @utbot.methodUnderTest {@link ProviderImpl#provideObject()}
     * @utbot.returnsFrom {@code return new ExampleClass(0);}
     */
    @Test
    @DisplayName("provideObject: -> return new ExampleClass(0)")
    public void testProvideObject_Return() {
        org.mockito.MockedConstruction mockedConstruction = null;
        try {
            java.util.concurrent.atomic.AtomicInteger mockClassCounter = new java.util.concurrent.atomic.AtomicInteger();
            mockedConstruction = mockConstruction(ExampleClass.class, (ExampleClass ExampleClassMock, org.mockito.MockedConstruction.Context context) -> {
                switch (mockClassCounter.get()) {
                    case 0:
                        break;
                }
                mockClassCounter.getAndIncrement();
            });
            ProviderImpl providerImpl = new ProviderImpl();

            ExampleClass actual = providerImpl.provideObject();

            ExampleClass expectedMock = mock(ExampleClass.class);
            expectedMock.field = 0;
            // org.utbot.examples.mock.service.impl.ExampleClass has overridden equals method
            assertEquals(expectedMock, actual);
        } finally {
            mockedConstruction.close();
        }
    }
    ///endregion

~~~

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.2.4
org.mockito:mockito-core:4.2.0

### PR DESCRIPTION
**Pull request by Damtev**
## Description

Fixes #1878.

### Automated tests

Common pipeline.

### Manual tests

The same as in the corresponding issue.

Generated test:
```java
///region Test suites for executable org.utbot.examples.mock.provider.impl.ProviderImpl.provideObject

///region SYMBOLIC EXECUTION: SUCCESSFUL EXECUTIONS for method provideObject()

/**
 * @utbot.classUnderTest {@link ProviderImpl}
 * @utbot.methodUnderTest {@link ProviderImpl#provideObject()}
 * @utbot.returnsFrom {@code return new ExampleClass(0);}
 */
@Test
@DisplayName("provideObject: -> return new ExampleClass(0)")
public void testProvideObject_Return() {
	org.mockito.MockedConstruction mockedConstruction = null;
	try {
		mockedConstruction = mockConstruction(ExampleClass.class, (ExampleClass ExampleClassMock, org.mockito.MockedConstruction.Context context) -> {
		});
		ProviderImpl providerImpl = new ProviderImpl();

		ExampleClass actual = providerImpl.provideObject();

		ExampleClass expectedMock = mock(ExampleClass.class);
		expectedMock.field = 0;
                // org.utbot.examples.mock.service.impl.ExampleClass has overridden equals method
                assertEquals(expectedMock, actual);
	} finally {
		mockedConstruction.close();
	}
}
///endregion
```

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [x] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

### CODE REVIEW

File: utbot-framework/src/main/kotlin/org/utbot/framework/codegen/renderer/CgJavaRenderer.kt [hunk 1]
```diff
@@ -314,8 +314,6 @@ internal class CgJavaRenderer(context: CgRendererContext, printer: CgPrinter = C
             for (statement in element.statements) {
                 statement.accept(this)
             }
-            // break statement in the end
-            CgBreakStatement.accept(this)
```
Comment (EgorkaKulikov) [inline utbot-framework/src/main/kotlin/org/utbot/framework/codegen/renderer/CgJavaRenderer.kt:318]: Please correct it as discussed

Comment (Damtev) [reply utbot-framework/src/main/kotlin/org/utbot/framework/codegen/renderer/CgJavaRenderer.kt:318]: Fixed

**Review by EgorkaKulikov — APPROVED** [review]
