### PR TITLE
Fix bug in FeatureProcessor

### LINKED ISSUE #223: FeatureProcessor dumps empty test cases
**Description**

Feature `.csv` files contains only header line.

**To Reproduce**

1. `UtSettings.enableFeatureProcess=true`
2. Run ContestEstimator
3. Look at files in `UtSettings.featurePath`

**Expected behavior**

Each file should contains feature rows for each state in test case.

**Actual behavior**

In `UtSettings.featurePath` all files contains only header line.

### PR DESCRIPTION
**Pull request by Atos1337**
# Description

Add `forEach` after `generateSequence`.

Fixes #223

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Automated Testing

org.utbot.features.FeatureProcessorWithRepetitionsTest

## Manual Scenario 

1. `UtSettings.enableFeatureProcess = true`
2. Run ContestEstimator
3. `UtSettings.featurePath` contains files with feature rows

### CODE REVIEW

File: utbot-analytics/src/test/java/org/utbot/features/OnePath.java [hunk 1]
```diff
@@ -0,0 +1,7 @@
+package org.utbot.features;
+
+public class OnePath {
```
Comment (amandelpie) [inline utbot-analytics/src/test/java/org/utbot/features/OnePath.java:3]: Please add some comments for this test feature

File: utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt [hunk 2]
```diff
@@ -52,7 +52,7 @@ class FeatureProcessorWithStatesRepetition(
         val states = mutableListOf<Pair<Int, Long>>()
         var newCoverage = 0
 
-        generateSequence(executionState) { currentState ->
+        generateSequence(executionState) { it.parent }.forEach { currentState ->
```
Comment (amandelpie) [inline utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt:55]: could it.parent be an empty or null?

**Review by amandelpie — APPROVED** [review]
It could merged after answering on minor comments from my side

File: utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt (hunk 2 above)
Comment (Atos1337) [reply utbot-analytics/src/main/kotlin/org/utbot/features/FeatureProcessorWithStatesRepetition.kt:55]: Yes, it can be null, if state is root, so we stop generation or if `UtSettings.enableFeatureProcess=false`, but in this case, we don't use `FeatureProcessor`
