### PR TITLE
Get rid of "Android" plugin dependency #934

### LINKED ISSUE #934: Get rid of "Android" plugin dependency
**Description**

We have some "com.android.*" imports and plugin fails if bundled "Android" plugin is disabled.
The task is to get rid of these imports.

**To Reproduce**

1. Disable "Android" plugin
2. Restart IDEA
3. Call "Generate tests..." action
4. Plugin fails

### PR DESCRIPTION
**Pull request by Vassiliy-Kudryashov**
# Description

Utility methods from com.android.* were replaced to platform API alternatives plus reflection.

Fixes #934 

- Refactoring

# How Has This Been Tested?

## Manual Scenario 

See the steps in relevant issue

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] No new warnings

### CODE REVIEW

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/util/IntelliJApiHelper.kt [hunk 1]
```diff
@@ -37,10 +37,19 @@ object IntelliJApiHelper {
     private val isAndroidPluginAvailable: Boolean = !PluginManagerCore.isDisabled(PluginId.getId("org.jetbrains.android"))
 
     fun isAndroidStudio(): Boolean =
-        isAndroidPluginAvailable && IdeInfo.getInstance().isAndroidStudio
+        isAndroidPluginAvailable && ("AndroidStudio" == PlatformUtils.getPlatformPrefix())
```
Comment (denis-fokin) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/util/IntelliJApiHelper.kt:40]: We need to move AS-specific code in a separate Gradle sub-project in future.

**Review by denis-fokin — APPROVED** [review]
