### PR TITLE
Make toMethodResult function safer

### LINKED ISSUE #1670: `RefType sun.nio.cs.UTF_8 not loaded` in `seata-core-0.5.0` project
**Description**
During test generation by ContestEstimator exceptions `RefType sun.nio.cs.UTF_8 not loaded` are thwrown.

**To Reproduce**

1. Open utbot project
2. Open `org.utbot.contest.ContestEstimatorKt` file
3. Set filters on project and class:
```
        methodFilter = "io.seata.core.protocol.transaction.GlobalBeginResponse.doEncode"
        projectFilter = listOf("seata-core-0.5.0")
```
4. Increase timeout if tests are not generated (val timeLimit = 120`)
5. Run `ContestEstimator`

**Expected behavior**
Tests are generated without errors

**Actual behavior**
There are errors in console output

```
11:35:31.655 | ERROR | Symbolic execution FAILED
java.lang.IllegalStateException: RefType sun.nio.cs.UTF_8 not loaded. If you tried to get the RefType of a library class, did you call loadNecessaryClasses()? Otherwise please check Soot's classpath.
	at soot.Scene.getRefType(Scene.java:1135) ~[soot-utbot-fork-4.4.0-FORK-2.jar:?]
	at org.utbot.engine.ResolverKt$toMethodResult$10.invoke(Resolver.kt:1214) ~[main/:?]
	at org.utbot.engine.ResolverKt$toMethodResult$10.invoke(Resolver.kt:1207) ~[main/:?]
	at org.utbot.engine.ResolverKt.arrayToMethodResult(Resolver.kt:1270) ~[main/:?]
	at org.utbot.engine.ResolverKt.toMethodResult(Resolver.kt:1207) ~[main/:?]
	at org.utbot.engine.Traverser.makeConcreteUpdatesForNonEnumStaticField(Traverser.kt:692) ~[main/:?]
	at org.utbot.engine.Traverser.processStaticFieldConcretely(Traverser.kt:600) ~[main/:?]
	at org.utbot.engine.Traverser.processStaticInitializer(Traverser.kt:490) ~[main/:?]
	at org.utbot.engine.Traverser.processStaticInitializerIfRequired(Traverser.kt:394) ~[main/:?]
	at org.utbot.engine.Traverser.doPreparatoryWorkIfRequired(Traverser.kt:366) ~[main/:?]
	at org.utbot.engine.Traverser.traverseStmt(Traverser.kt:329) ~[main/:?]
	at org.utbot.engine.Traverser.traverse(Traverser.kt:312) ~[main/:?]
	at org.utbot.engine.UtBotSymbolicEngine$traverseImpl$1.invokeSuspend(UtBotSymbolicEngine.kt:301) [main/:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.7.20.jar:1.7.20-release-201(1.7.20)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.6.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_352]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_352]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
11:35:32.786 | DEBUG | --new testCase collected, to generate: testIo.seata.core.protocol.transaction.GlobalBeginResponse.doEncode6
```

### PR DESCRIPTION
**Pull request by CaelmBleidd**
# Description

Replace in the `toMethodResult` function unsafe access to soot classes with a safe one (surprisingly called `unsafe`). If we cannot upload a concrete type from the Runtime, we create an unbounded variable with a type belonging to a field we construct.

Fixes #1670 

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Regression and integration tests

There are no regression tests since it is quite hard to imitate the problem since it'd require working with a "broken" classpath.

## Automated Testing

There are no automatic tests due for the same reason.

## Manual Scenario 

Run contest estimator reproducing steps from #1670 and check that there are no produced errors.

# Checklist:

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] No new warnings
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-framework/src/main/kotlin/org/utbot/engine/Resolver.kt [hunk 1]
```diff
@@ -1235,7 +1235,15 @@ fun Traverser.toMethodResult(value: Any?, sootType: Type): MethodResult {
 
                 val createdElement = if (elementType is RefType) {
                     val className = value[it]!!.javaClass.id.name
-                    createObject(addr, Scene.v().getRefType(className), useConcreteType = true)
+                    // Try to take an instance of class we find in Runtime
+                    // If it is impossible, take the default `elementType` without a concrete type instead.
+                    val (type, useConcreteType) =
+                        Scene.v().getSootClassUnsafe(className)
+                            ?.type
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Resolver.kt:1242]: Wgy not `getRefTypeUnsafe`?

File: utbot-framework/src/main/kotlin/org/utbot/engine/Resolver.kt [hunk 2]
```diff
@@ -1262,7 +1270,15 @@ fun Traverser.toMethodResult(value: Any?, sootType: Type): MethodResult {
 
                 return asMethodResult {
                     val addr = UtAddrExpression(mkBVConst("staticVariable${value.hashCode()}", UtInt32Sort))
-                    createObject(addr, Scene.v().getRefType(refTypeName), useConcreteType = true)
+                    // Try to take a type from an object from the Runtime.
+                    // If it is impossible, create an instance of a default `sootType` without a concrete type.
+                    val (type, useConcreteType) = Scene.v()
+                        .getSootClassUnsafe(refTypeName)
+                        ?.type
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Resolver.kt:1277]: Same

**Review by Damtev — APPROVED** [review]
