### PR TITLE
Do not miss non-injected fields in Spring unit test generation

### LINKED ISSUE #2386: Failing Spring unit test is generated (possibly due to incorrect injection)
**To Reproduce**

Consider generating unit tests for project `spring-boot-testing` with modified `OrderService` class.

```java
@Service
public class OrderService {

    @Autowired
    private OrderRepository orderRepository;

    private List<Order> baseOrders = new ArrayList<>();

    public int getOrdersCount() { return orderRepository.findAll().size() + baseOrders.size(); }
}

```

**Expected behavior**

Happy pass test is generated with correct assertions.

**Actual behavior**

The following failing test is generated.
It fails because real number of items in collection is 3, not 6.

```java
@Test
    @DisplayName("getOrdersCount: OrderRepositoryFindAll -> return orderRepository.findAll().size() + baseOrders.size()")
    public void testGetOrdersCount_ListSize() {
        ArrayList arrayList1 = new ArrayList();
        arrayList1.add(null);
        arrayList1.add(null);
        arrayList1.add(null);
        (when(orderRepositoryMock.findAll())).thenReturn(arrayList1);

        int actual = orderService.getOrdersCount();

        assertEquals(6, actual);
    }
```

### PR DESCRIPTION
**Pull request by tepa46**
## Description

Fixes #2386
 
Now a separate `SetField()` is prescribed for non-Mock fields

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [x] The **documentation** for the functionality I've been working on is up-to-date.

### CODE REVIEW

**Review by EgorkaKulikov — APPROVED** [review]

File: utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringVariableConstructor.kt [hunk 1]
```diff
@@ -23,13 +23,18 @@ class CgSpringVariableConstructor(context: CgContext) : CgVariableConstructor(co
...
+            val modelFields = when (model) {
+                is UtCompositeModel -> model.fields
+                is UtAssembleModel -> model.origin?.fields
+                else -> null
             }
 
-            fields.forEach { getOrCreateVariable(it) }
+            modelFields?.forEach{ (fieldId, fieldModel) ->
+                val variableForField = getOrCreateVariable(fieldModel)
+                if(!fieldModel.isMockModel()) {
```
Comment (EgorkaKulikov) [inline utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringVariableConstructor.kt:34]: Please add a comment like this

```
// If field model is a mock, it is set in the connected with instance under test automatically via @InjectMocks;
// Otherwise we need to set this field manually.
```
