### PR TITLE
Remember selections in python dialog

### LINKED ISSUE #1563: Remember selection of dialog options for Python test generation
**Description**
When user selects for example non default Test framework during test generation for Python then next time it's reset to default value. The same with other fields, with exception of 'Test source root'

**To Reproduce**

1. Open Python project
2. Invoke test generation dialog
3. Select `Test framework = pytest`
4. Generate tests
5. Invoke the dialog again

**Expected behavior**

`pytest` test framework is preserved

**Actual behavior**

test framework is `Unittest` again

image

**Additional context**

The same is with both timeouts and 'Visit only specified source'

### PR DESCRIPTION
**Pull request by tamarinvs19**
## Description

Add saving and loading selections in dialog options same as for UtBotJava

Fixes #1563 

### Manual tests

1. Generate tests for python functions or classes after changing settings (TestFramework / Timout)
2. Try to generate again
3. __Expected__: settings have been recovered

## Self-check list

Check off the item if the statement is true. Hint: [x] is a marked item.

Please do not delete the list or its items.

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

### CODE REVIEW

File: utbot-intellij-python/src/main/kotlin/org/utbot/intellij/plugin/language/python/PythonDialogWindow.kt [hunk 1]
```diff
@@ -59,36 +65,42 @@ class PythonDialogWindow(val model: PythonTestsModel) : DialogWrapper(model.proj
...
-                    component(timeoutSpinnerForTotalTimeout)
-                    label("seconds")
-                    component(ContextHelpLabel.create("Set the timeout for all test generation processes."))
-                }
+            row("Test generation timeout:") {
+                cell(BorderLayoutPanel().apply {
+                    addToLeft(timeoutSpinnerForTotalTimeout)
+                    addToRight(JBLabel("seconds per function"))
+                })
+                contextHelp("Set the timeout for all test generation processes per function to complete.")
```
Comment (tochilinak) [inline utbot-intellij-python/src/main/kotlin/org/utbot/intellij/plugin/language/python/PythonDialogWindow.kt:80]: Previously this was timeout for all functions (not 'per function'). Has this changed?

Comment (tamarinvs19) [reply utbot-intellij-python/src/main/kotlin/org/utbot/intellij/plugin/language/python/PythonDialogWindow.kt:80]: Thanks, it is incorrect description. It should be 'per file' or 'per module' because I run one test generation process per one file.

**Review by tochilinak — APPROVED** [review]
