### PR TITLE
Intellij IDEA IU plugin size fix

### LINKED ISSUE #1421: Intellij IDEA IU plugin size is too big
**Description**

Intellij IDEA IU is required to support UTBot JS. However, .jar distributable is 190 MB, which seems too much for a plugin.

**Expected behavior**

Make distributable size less to make it more accessible for users.

### PR DESCRIPTION
**Pull request by zishkaz**
# Description

IU version of .jar plugin was 190 MB, which was considered too much. This PR makes IU plugin size 134 MB.

Fixes #1421 

## Type of Change

- Minor bug fix (non-breaking small changes)

# How Has This Been Tested?

## Automated Testing

None.

## Manual Scenario 

Links to GitHub actions that contain IU plugin .jar:
Size before: https://github.com/UnitTestBot/UTBotJava/actions/runs/3419239979
Size after: https://github.com/UnitTestBot/UTBotJava/actions/runs/3543187829

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] New tests have been added
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-js/src/main/kotlin/parser/JsFunctionAstVisitor.kt [hunk 1]
```diff
@@ -1,32 +1,35 @@
...
-        functionNode?.let {
-            if (it.name.toString() == target && (className ?: "") == lastVisitedClassName) {
-                targetFunctionNode = it
-                return false
+    override fun accept(rootNode: Node) {
+        NodeUtil.visitPreOrder(rootNode) { node ->
+            when {
+                node.isMemberFunctionDef -> {
+                    val name = node.getAbstractFunctionName()
+                    if (name == target && node.parent!!.parent!!.getClassName() == className) {
```
Comment (denis-fokin) [inline utbot-js/src/main/kotlin/parser/JsFunctionAstVisitor.kt:20]: Do you want to have an NPE here? or handle null as a non-equal value?

Comment (zishkaz) [reply utbot-js/src/main/kotlin/parser/JsFunctionAstVisitor.kt]: Rewrote to better exception handlers

**Review by EgorkaKulikov — APPROVED** [review]
It seems to be an important step to move UTBot to a significantly new quality level.  :smiley_cat::smiley_cat:
