### PR TITLE
Concrete executor reflection fix

### LINKED ISSUE #1305: Fuzzing mode with JDK 13/17 `CommonMocksExample.nextValue`. 343 errors in Concrete Executor
**Description**

Fuzzing test generation for `CommonMocksExample.nextValue`. 343 errors in Concrete Executor

**To Reproduce**

1. Install [plugin built from the latest main](https://github.com/UnitTestBot/UTBotJava/actions/runs/3415798879) into IDEA 2022.2.3
2. Create IntelliJ project with **_JDK 13 / 17_** - _not reproducing with JDK 11._
3. Create CommonMocksExample java class:

```java
public class CommonMocksExample {
    public RecursiveTypeClass nextValue(RecursiveTypeClass node) {
        if (node.next == node) {
            return node;
        }

        node.next.value = node.value + 1;

        return node;
    }
}
```

4. Create RecursiveTypeClass in the same package

```java
public class RecursiveTypeClass {
    public RecursiveTypeClass next;
    public int value;
}

```
5. Generate tests for CommonMocksExample 
6. Open the generated test

**Expected behavior**

Tests are supposed to be generated without errors.

**Actual behavior**

An error test is generated with information about 343 errors in the concrete executor.

**Visual proofs (screenshots, logs, images)**

~~~java
    ///region Errors report for nextValue

    public void testNextValue_errors() {
        // Couldn't generate some tests. List of errors:
        // 
        // 343 occurrences of:
        // Default concrete execution failed

    }
    ///endregion
~~~

There are 344 exceptions with the following stack trace:

```java
Error | ChildProcess              | 18:Scheduler for Client57486 |  | java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
	at org.utbot.framework.concrete.MockValueConstructor.constructObject(MockValueConstructor.kt:190)
	at org.utbot.framework.concrete.MockValueConstructor.construct(MockValueConstructor.kt:130)
	at org.utbot.framework.concrete.MockValueConstructor.constructMethodParameters(MockValueConstructor.kt:107)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:153)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:116)
	at org.utbot.instrumentation.process.ChildProcessKt$setup$2.invoke(ChildProcess.kt:125)
	at org.utbot.instrumentation.process.ChildProcessKt$setup$2.invoke(ChildProcess.kt:121)
	at org.utbot.rd.CallsSynchronizer$measureExecutionForTermination$1$1.invoke(ClientProcessUtil.kt:84)
	at org.utbot.rd.CallsSynchronizer.measureExecutionForTermination(ClientProcessUtil.kt:75)
	at org.utbot.rd.CallsSynchronizer$measureExecutionForTermination$1.invoke(ClientProcessUtil.kt:83)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182)
	at com.jetbrains.rd.framework.impl.RdCall.onWireReceived(RdTask.kt:360)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:148)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:54)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase.queue$lambda-3(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Environment**

IntelliJ IDEA 2022.2.3

### PR DESCRIPTION
**Pull request by Domonion**
Setting Field.modifiers accessible fix.
Moving child process debug switch to UtSettings

Fixes #1305

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: utbot-core/src/main/kotlin/org/utbot/common/Logging.kt [hunk 1]
```diff
@@ -68,11 +68,20 @@ inline fun <T> LoggerWithLogMethod.bracket(
...
+inline fun <T> KLogger.catchException(block: () -> T): T? {
     return try {
         block()
     } catch (e: Throwable) {
         this.error(e) { "Isolated" }
         null
     }
 }
+
+inline fun <T> KLogger.logException(block: () -> T): T? {
```
Comment (sergeypospelov) [inline utbot-core/src/main/kotlin/org/utbot/common/Logging.kt:80]:
```suggestion
inline fun <T> KLogger.logException(block: () -> T): T {
```
