### PR TITLE
Fix no targets for invocation for abstract this type

### LINKED ISSUE #1624: No targets for invocation error on antlr
**Description**

An error occurred during generation for `org.antlr.v4.codegen.Target.getTemplates`

```
java.lang.IllegalArgumentException: No targets for Invocation(instance=ObjectValue(typeStorage=org.antlr.v4.codegen.Target, addr=addr: (BVInt32 p_this)), method=<org.antlr.v4.codegen.Target: org.stringtemplate.v4.STGroup getTemplates()>, parameters=[], generator=() -> kotlin.collections.List<org.utbot.engine.InvocationTarget>)
	at org.utbot.engine.Traverser.commonInvokePart(Traverser.kt:2707)
	at org.utbot.engine.Traverser.virtualAndInterfaceInvoke(Traverser.kt:2498)
```

**To Reproduce**

_Example:_

1. Run the contest estimator for org.antlr.v4.codegen.Target.getTemplates with 120s time limit
2. Check the results

**Expected behavior**

Execution without errors.

**Actual behavior**

An error encountered.

**Visual proofs (screenshots, logs, images)**

Not applicable.

**Environment**

There is no specific environment.

**Additional context**

There is no additional context.

### PR DESCRIPTION
**Pull request by CaelmBleidd**
# Description

Add support for testing methods of the abstract classes which have instantiable inheritors. Early we didn't check whether we can create a `this` instance or not, now we can replace it with its inheritors if there is such an inheritors with non-overridden method under test.

Fixes #1624 

## Type of Change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Regression and integration tests

The same as automatic tests/

## Automated Testing

`org.utbot.examples.objects.AbstractAnonymousClassTest#testNonOverriddenMethod`

## Manual Scenario 

Run the contest estimator for `org.antlr.v4.codegen.Target.getTemplates` and check that there are no errors.

# Checklist:

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [x] New tests have been added
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 1]
```diff
@@ -1365,7 +1365,40 @@ class Traverser(
...
+                // the method under test
+                if (isTypeInappropriate) {
+                    val possibleTypesWithNonOverriddenMethod = possibleTypes
+                        .filterTo(mutableSetOf()) {
+                            val methods = (it as RefType).sootClass.methods
+                            methods.none { method ->
+                                val methodUnderTest = environment.method
+                                val parameterTypes = method.parameterTypes
+
+                                method.name == methodUnderTest.name && parameterTypes == methodUnderTest.parameterTypes
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:1384]: `contentEquals` should be used here, I guess

**Review by Damtev — CHANGES_REQUESTED** [review]

**Review by Damtev — APPROVED** [review]
