### PR TITLE
Skip test generation for abstract methods #550

### LINKED ISSUE #550: Exceptions are thrown when trying to generate tests for abstract classes
**Description**

Currently, if you pass methods from abstract classes to tests generator, you are likely to have an uncaught exception that will ruin test generation 

**To Reproduce**

Launch the plugin on a class C in this example:
```Java
abstract class C {
    abstract public int f();
}

class Cimpl extends C {
    @Override
    public int f() { return 0; }
}
```

**Expected behavior**

No tests are generated and C.f() is not even proposed for testing in dialog.

**Actual behavior**

Plugin shows a dialog with C.f() method. After launching plugin fails with `IllegalArgumentException`.

**Visual proofs (screenshots, logs, images)**

```
java.lang.IllegalArgumentException: Can't retrieve body for <rndpkg.C: int f()>
	at org.utbot.engine.ExtensionsKt.jimpleBody(Extensions.kt:114)
	at org.utbot.framework.util.SootUtilsKt.jimpleBody(SootUtils.kt:102)
	at org.utbot.engine.UtBotSymbolicEngine.<init>(UtBotSymbolicEngine.kt:157)
	at org.utbot.framework.plugin.api.TestCaseGenerator.createSymbolicEngine(TestCaseGenerator.kt:278)
	at org.utbot.framework.plugin.api.TestCaseGenerator.access$createSymbolicEngine(TestCaseGenerator.kt:51)
	at org.utbot.framework.plugin.api.TestCaseGenerator$generate$4$1$1.invokeSuspend(TestCaseGenerator.kt:166)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.utbot.common.ConcurrencyKt.runBlockingWithCancellationPredicate(Concurrency.kt:38)
	at org.utbot.framework.plugin.api.TestCaseGenerator$generate$4.invoke(TestCaseGenerator.kt:158)
	at org.utbot.framework.plugin.api.TestCaseGenerator$generate$4.invoke(TestCaseGenerator.kt:51)
	at org.utbot.common.ConcurrencyKt.runIgnoringCancellationException(Concurrency.kt:47)
	at org.utbot.framework.plugin.api.TestCaseGenerator.generate(TestCaseGenerator.kt:157)
	at org.utbot.framework.plugin.api.TestCaseGenerator.generate$default(TestCaseGenerator.kt:144)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor$createTests$2$1.run(UtTestsDialogProcessor.kt:196)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Environment**

Generate for Java, JUnit5 with Mockito static mocking.

**Additional context**

Similar problems happen when you try to generate tests for abstract classes that has no implementations. 

See also #221.

### PR DESCRIPTION
**Pull request by volivan239**
# Description

* Added filters for abstract methods, so now they don't reach test generator
* Added catch for exception which is thrown when plugin tries to generate tests for an abstract class that has no implementations (in this case error message is shown in UI)

Fixes #550

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Automated Testing

No tests were added.

## Manual Scenario 

* Launch plugin on example from #550 -- works as expected.
* Launch plugin on a package with abstract class with default functions and no derived classes -- test generation for this class is skipped and an error message is shown.

# Checklist (remove irrelevant options):

- [ ] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

### CODE REVIEW

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt [hunk 1]
```diff
@@ -361,6 +362,7 @@ class GenerateTestsDialogWindow(val model: GenerateTestsModel) : DialogWrapper(m
         if (srcClasses.size == 1) {
             items = TestIntegrationUtils.extractClassMethods(srcClasses.single(), false)
                 .filterWhen(UtSettings.skipTestGenerationForSyntheticMethods) { it.member !is SyntheticElement }
+                .filterNot { it.member.modifierList?.hasModifierProperty(PsiModifier.ABSTRACT)?: false }
```
Comment (Damtev) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt:365]: Please, move such a function somewhere in utils.

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt [hunk 2]
```diff
@@ -191,11 +193,16 @@ object UtTestsDialogProcessor {
...
-                                            .map { it.summarize(searchDirectory) }
-                                            .filterNot { it.executions.isEmpty() && it.errors.isEmpty() }
+                                    val notEmptyCases = try {
+                                        withUtContext(context) {
+                                            testCaseGenerator
+                                                .generate(methods, model.mockStrategy, model.chosenClassesToMockAlways, model.timeout)
+                                                .map { it.summarize(searchDirectory) }
+                                                .filterNot { it.executions.isEmpty() && it.errors.isEmpty() }
+                                        }
+                                    } catch (e: java.lang.IllegalStateException) {
```
Comment (Damtev) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt:203]: Are we really going to catch only `IllegalStateException`? Maybe, we should catch every exception here? Need to discuss

**Review by Damtev — CHANGES_REQUESTED** [review]

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt (hunk 1 above)
Comment (volivan239) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt]: Moved to `org.utbot.intellij.plugin.util.MemberInfoUtilsKt#isAbstract`

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt (hunk 2 above)
Comment (volivan239) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt]: As discussed, replaced with `runCatching`

**Review by Damtev — APPROVED** [review]
