### PR TITLE
Concrete executor logs

### LINKED ISSUE #870: Log of concrete execution doesn't print exception anymore
**Description**

At the moment, logs that are created by concrete execution don't contains printed exception anymore, but have too much info about data transfer between main process and child process.

**To Reproduce**

1. Enable logs using `~/.utbot/settings.properties`: `logConcreteExecutionErrors=true`
2. Run any test generation which leads to concrete execution failure. For example, #739
3. Find logs in temp folder: `~\AppData\Local\Temp\UTBot\utbot-childprocess-errors`
4. Open it.

**Expected behavior**

Log should contain some system information and an exception that is translated into broken test in main process.

**Actual behavior**

Log contains some child process problem (#848), many lines like this one:

```
16:59:27.308 | sent cmd: org.utbot.framework.concrete.UtConcreteExecutionResult@2efe6272
````

and no information about exception.

**Additional context**

Looks like this behavior was introduces with #748

### PR DESCRIPTION
**Pull request by Domonion**
# Description

Fixes #870
Moved logs in `RuntimeTraceStorage` and `DynamicClassTransformer` to ChildProcess.kt logging system

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/et/TraceHandler.kt [hunk 1]
```diff
@@ -151,7 +152,7 @@ object RuntimeTraceStorage {
             this.`$__trace__`[current] = id
             this.`$__counter__` = current + 1
         } else {
-            System.err.println("Stack overflow (increase stack size Settings.TRACE_ARRAY_SIZE)")
+            logDebug { "Stack overflow (increase stack size Settings.TRACE_ARRAY_SIZE)" }
```
Comment (sergeypospelov) [inline utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/et/TraceHandler.kt:155]:
```suggestion
            if (alreadyLoggedIncreaseStackSizeTip) {
                logError { "Stack overflow (increase stack size Settings.TRACE_ARRAY_SIZE)" }
            }
```

Comment (sergeypospelov) [reply utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/et/TraceHandler.kt:155]: `alreadyLoggedIncreaseStackSizeTip` can be a private util variable in `RuntimeStorage`.

**Review by sergeypospelov — CHANGES_REQUESTED** [review]

**Review by sergeypospelov — APPROVED** [review]
