### PR TITLE
Fixed improper verification of the mocha installation

### LINKED ISSUE #1582: Improper verification of the installation of the mocha test framework
**Description**

Currently, only global installations of npm packages are checked. Due to the pull request #1566, where the installation of mocha was moved to the local one, it is necessary to check whether mocha is installed locally in the repository.

1. Run UTBot plugin with JavaScript 
2. Try to generate unit-tests

**Expected behavior**

Checking the installed mocha package should occur correctly, if there is a local mocha installation, a window with an installation suggestion should not appear.

**Actual behavior**

For each iteration, the mocha installation window appears even if mocha is installed locally manually.

### PR DESCRIPTION
**Pull request by rudolf101**
# Description
Now the installed mocha package is checked correctly, if there is a local mocha installation, the window with the installation suggestion does not appear.
Fixes #1582

## Type of Change

Please delete options that are not relevant.

- Minor bug fix (non-breaking small changes)

# How Has This Been Tested?
Manually 

## Manual Scenario 
* If mocha is not installed on the system, the user will be prompted to download mocha
* Otherwise, the plugin window will appear without a download suggestion

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] No new warnings
- [x] All manual scenarios pass locally with my changes

### CODE REVIEW

File: utbot-intellij-js/src/main/kotlin/org/utbot/intellij/plugin/language/js/Utils.kt [hunk 1]
```diff
@@ -22,24 +22,30 @@ fun getFrameworkLibraryPath(npmPackageName: String, model: JsTestsModel?): Strin
...
         shouldWait = true,
         timeout = 10,
-        cmd = arrayOf(model.pathToNPM, "list", "-g")
+        cmd = arrayOf(model.pathToNPM, "list", flag)
     )
-    val checkForPackageText = bufferedReader.readText()
-    bufferedReader.close()
-    if (checkForPackageText == "") {
+    val packages = bufferReader.readText()
+    bufferReader.close()
```
Comment (denis-fokin) [inline utbot-intellij-js/src/main/kotlin/org/utbot/intellij/plugin/language/js/Utils.kt:33]: Is that correct that you close the reader for the input stream and do not close for the error stream (which is created in runCommand)?

**Review by denis-fokin — APPROVED** [review]
