### PR TITLE
Generate DisplayName annotation only for JUnit 5 #576

### LINKED ISSUE #576: Generated tests contain JUnit4 @Test and commented JUnit5 @DisplayName annotations
**Description**

Tests generated with JUnit4 framework selected - contain JUnit4 @Test and commented JUnit5 @DisplayName annotations.

**To Reproduce**

1. IntelliJ IDEA with UTBot plugin installed is opened
2. Open a project with JDK 8-11
3. Open a public class with a public method
4. Use plugin to generate tests with JUnit4 test framework selected

**Expected behavior**

Only JUnit4 annotations are supposed to be used.

**Actual behavior**

@org.junit.jupiter.api.DisplayName are present, though commented

**Visual proofs (screenshots, logs, images)**

```
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class BinarySearchTest {
...
    @Test
    //@org.junit.jupiter.api.DisplayName("rightBinSearch: array = long[10], key = 0L -> return 10")
    public void testRightBinSearchReturns10WithNonEmptyPrimitiveArrayAndCornerCase() {
...
```

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.1.3
UTBot plugin version: https://github.com/UnitTestBot/UTBotJava/actions/runs/2717703384

### PR DESCRIPTION
**Pull request by onewhl**
# Description

Add a single line comment with a short description for JUnit4.
Generate `@DisplayName` annotation only for JUnit5.
Add a value for `description` argument for TestNG.
Fixes #576

Screenshots for JUnit4, JUnit5, and TestNG respectively:
junit4
junit5
testng

**UPDATE**: decided to not show a display name in case of JUnit4 and to not add a single line comment.

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Automated Testing

Run summary tests.

## Manual Scenario 

Generate tests using different test frameworks: JUnit4, JUnit5, TestNG and check test annotations and comments.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] New tests have been added
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt [hunk 1]
```diff
@@ -1599,7 +1599,23 @@ internal class CgMethodConstructor(val context: CgContext) : CgContextOwner by c
...
+        if (displayName != null) {
+            when (testFramework) {
+                is Junit5 -> {
+                    displayName.let { testFrameworkManager.addDisplayName(it) }
+                }
+                is TestNg -> {
+                    testFrameworkManager.addTestDescription(displayName)
+                }
+                else -> {
+                    // nothing
```
Comment (amandelpie) [inline utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt:1615]: I suggest to create a ticket to add a custom Java tag for display name as @displayname or @summary for JUnit 4

Comment (amandelpie) [reply utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt:1615]: It's weird that we just forget the generated display name :( for JUnit4 but generates it.

No logging in this file at all, it's sad too

File: utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt [hunk 2]
```diff
@@ -1645,12 +1661,19 @@ internal class CgMethodConstructor(val context: CgContext) : CgContextOwner by c
...
                 CgDocumentationComment(text = null)
             } else {
                 CgDocumentationComment(docComment)
             }
+            documentation.add(documentationComment)
+
+            /* JUnit4 doesn't have DisplayName annotation and any other suitable for putting short description,
+               that's why we add a single line comment below JavaDoc with a test's short description.
+             */
+            if (testFramework is Junit4 && displayName != null) {
```
Comment (amandelpie) [inline utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt:1674]: Probably we don't need this short commented summary under the test, it looks weird and clashes with the JavaDocs

**Review by amandelpie — APPROVED** [review]

File: utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt (hunk 2 above)
Comment (onewhl) [reply utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt:1674]: I agree that single-line comment below JavaDoc might look weird, but it contains short useful information about the test. As you suggested in another comment, we can add a custom JavaDoc tag for it in future.

Comment (denis-fokin) [reply utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt:1674]: Agreed, that the comment line does not look good. I am even not sure, that an average user will understand what it is.

Comment (onewhl) [reply utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt]: Fixed as discussed, now we don't show display name in case of JUnit4.

**Review by denis-fokin — APPROVED** [review]
