### PR TITLE
Fuzzing consume much memory for a method with 10 and more parameters

### LINKED ISSUE #293: Fuzzing consume much memory for a method with 10 and more parameters
**Description**

Fuzzer creates an array for all combinations to randomize input combinations. It may lead to high memory consumption.

**To Reproduce**

Try to run fuzzing on method with 10 and more parameters.

**Expected behavior**

Fuzzing runs without a high memory consumption.

**Actual behavior**

There's an array that takes much memory. For example, this one was found for a method with 10 different parameters:

```
int[6553600], GC Root: Java Frame: org.utbot.fuzzer.CartesianProduct.iterator(CartesianProduct.kt:19) 
```

### PR DESCRIPTION
**Pull request by Markoutte**
# Description

Provides another way to randomize fuzzer generated values. This approach helps to create a sequence of shuffled unique integers  without huge memory consumption for corner cases. Previously, it was creating an array for storing as much integers as fuzzer had possible values combinations thus it leads to OOME.

Fixes #293

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Automated Testing

Run PseudoShuffledIntProgressionTest to validate that an implementation is correct.

## Manual Scenario 

Create a test with 10 parameters:

```java
    public int test(int x, boolean y, String s, Integer z, float f, double g,
                    int x2, boolean y3, String s4, Integer z5, float f6, double g2) {
        return -1;
    }
```

Run test generation with fuzzer and capture memory snapshot. Find `org.utbot.fuzzer.PseudoShuffledIntProgression` object and check that retained size isn't big (in my case for 6 553 600 values it takes only 20 596 bytes).

### CODE REVIEW

File: utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+ * In general there are 2 ways to get random order for a given range:
+ * 1. Create an array of target size and shuffle values.
+ * 2. Create a set of generated values and generate new values until they're unique.
+ *
+ * Both cases cause high memory usage when target number of values is big.
+ *
+ * The memory usage can be reduced by using a pseudo-random sequence.
+ *
+ * Algorithm to create pseudo-random sequence:
+ * 1. Separate a sequence into 2 parts: matrix-part and tail
```
Comment (CaelmBleidd) [inline utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt:18]: How do we separate them? From the example we can see, that we transform the sequence into `n * n` matrix with a `size - n * n` tail. Is it always true?

File: utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+ *
+ */
+class PseudoShuffledIntProgression : Iterable<Int> {
+    private val top: IntArray
+    private val left: IntArray
+    private val tail: IntArray
+
+    val size: Int
+
+    constructor(size: Int, random: Random = Random) : this (size, random, { sqrt(it.toDouble()).toInt() })
```
Comment (CaelmBleidd) [inline utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt:77]: extra space

File: utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+        check(size >= 0) { "Size must be positive or 0 but current value is $size" }
+        this.size = size
+        var topSize = side(size)
+        if (topSize > 0 && topSize > size / topSize) {
+            topSize = size / topSize
+        }
+        check(topSize > 0 || size == 0) { "Side of matrix must be greater than 0 but $topSize <= 0" }
+
+        top = IntArray(size = topSize) { it }.apply { shuffle(random) }
+        left = IntArray(size = if (topSize == 0) 0 else size / topSize) { it }.apply { shuffle(random) }
```
Comment (CaelmBleidd) [inline utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt:92]: How `topSize` can be equal to zero here? We checked that it must be positive

Comment (CaelmBleidd) [reply utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt:92]: Can you add a description for the fields, please? Or, probably, it is better to change names. I believe, `top` is the number of the columns and `left` is the number of the rows?

File: utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+            }
+            top[i] * l + left[j]
+        }
+    }
+
+    fun toArray(): IntArray = IntArray(size, this::get)
+
+    override fun iterator(): IntIterator = object : IntIterator() {
+        var current = 0
+        override fun hasNext() = current < size
```
Comment (CaelmBleidd) [inline utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt:136]: Is it right? We stated that it `Generates pseudo random values from 0 to size exclusive.`

File: utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt [hunk 5]
```diff
@@ -0,0 +1,139 @@
...
+ * ```
+ * matrix             tail
+ * -----------------------
+ *  0  5 10 15        20
+ *  1  6 11 16        21
+ *  2  7 12 17        22
+ *  3  8 13 18
+ *  4  9 14 19
+ * ```
+ * Columns are shuffled:
```
Comment (CaelmBleidd) [inline utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt:34]: Can you add an extended explanation, please? Not only with the matrix but with `top` and `left` arrays as well

File: utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt [hunk 6]
```diff
@@ -0,0 +1,139 @@
...
+        var j = index / e
+        return if (i == t && j < tail.size) {
+            tail[j]
+        } else {
+            val o = ((index - tail.size * e) / t).toLong()
+            if (o > 0) {
+                i = ((index + o) % e).toInt()
+                j = ((index + o) / e).toInt()
+            }
+            top[i] * l + left[j]
```
Comment (CaelmBleidd) [inline utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt:128]: Can you add an example, just like you added for the whole algorithm, please?  For me, it is not obvious work with `tail.size * e`

**Review by CaelmBleidd — CHANGES_REQUESTED** [review]
Some places are a bit confusing at first sight, but everything seems fine

File: utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt (hunk 3 above)
Comment (Markoutte) [reply utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt:92]: > How topSize can be equal to zero here? We checked that it must be positive

Top size can be 0 in case when size is 0. Both arrays should be 0 in this case

File: utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt (hunk 4 above)
Comment (Markoutte) [reply utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt:136]: Looks like yes, because for size 10 we want to generate sequence like [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]. Added a test on this

File: utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt (hunk 1 above)
Comment (Markoutte) [reply utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/PseudoShuffledIntProgression.kt]: Rewrite this algorithm to clarify this place

**Review by CaelmBleidd — APPROVED** [review]
LGTM
