### PR TITLE
Prohibit to set static fields from library classes #697

### LINKED ISSUE #697: Engine sets the hidden `SecurityManager` static field
**Description**

Engine produces `staticsBefore` with the hidden `SecurityManager` static field. The concrete executor can't find this field, so it isn't present in `staticsAfter`. This leads to test generation failure as we expect `staticsBefore` and `staticsAfter` to have the same structure. 

**To Reproduce**

1. Create this method:
```java
    public void createThread() {
        final int[] x = {0};
        new Thread(() -> {
            x[0]++;
        }).start();
        new Thread(() -> {
            x[0]++;
        }).start();
    }
```
2. Run test generation via UtBot plugin

**Expected behavior**

At least one test generated and there are no tests with internal exceptions.

**Actual behavior**

There is a generated test with an internal exception.

**Visual proofs (screenshots, logs, images)**

image

### PR DESCRIPTION
**Pull request by sergeypospelov**
# Description

- It's prohibited now to set static fields from predefined library classes. This is done by filtering fields which are added to `meaningfulStaticFields` in `Traverser`. Also these fields won't be substituted with unbounded symbolic variables.
- Add flag in `UtSettings` for this feature.
- Refactored `initializedStaticFields` field in `Memory`.
- Refactored docs for `WorkaroundReason`.

Fixes #697

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Manual Scenario 

**To reproduce** section from #697 works correctly.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] No new warnings
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 1]
```diff
@@ -1780,13 +1781,19 @@ class Traverser(
...
         }
 
         return createdField
     }
 
+    private fun isStaticFieldMeaningful(field: SootField) =
+        !Modifier.isSynthetic(field.modifiers) &&
+            // we don't want to set fields from library classes
+            !javaPackagesToProcessConcretely.any { field.declaringClass.packageName.startsWith(it) } &&
+            !sunPackagesToProcessConcretely.any { field.declaringClass.packageName.startsWith(it) }
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:1795]: Maybe we can use `org.utbot.framework.TrustedLibraries#getTrustedLibraries` here?

**Review by Damtev — CHANGES_REQUESTED** [review]

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt (hunk 1 above)
Comment (sergeypospelov) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt]: Didn't know about that, thank you.

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 2]
```diff
@@ -1780,13 +1783,20 @@ class Traverser(
...
         }
 
         return createdField
     }
 
+    private fun isStaticFieldMeaningful(field: SootField) =
+        !Modifier.isSynthetic(field.modifiers) &&
+            // we don't want to set fields from library classes
+            workaround(IGNORE_STATICS_FROM_TRUSTED_LIBRARIES) {
+                !ignoreStaticsFromTrustedLibraries || !field.declaringClass.isFromTrustedLibrary()
```
Comment (CaelmBleidd) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:1797]: I think it is better to rewrite with conjunction to avoid several negations

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 3]
```diff
@@ -3321,10 +3331,11 @@ class Traverser(
         val updatedFields = staticFieldsUpdates.mapTo(mutableSetOf()) { it.fieldId }
         val objectUpdates = mutableListOf<UtNamedStore>()
 
-        // we assign unbounded symbolic variables for every non-final field of the class
+        // we assign unbounded symbolic variables for every non-final meaningful field of the class
+        // fields from predefined library classes are excluded, because there are not meaningful
```
Comment (CaelmBleidd) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:3335]: It is better to explain somewhere what you mean `meaningful`

**Review by CaelmBleidd — APPROVED** [review]
LGTM

**Review by dtim — APPROVED** [review]
I agree with comments by @CaelmBleidd (especially w.r.t. condition readability in `isStaticFieldMeaningful`), but LGTM overall.

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt (hunk 2 above)
Comment (sergeypospelov) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt]: I agree, thank you.

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt (hunk 3 above)
Comment (sergeypospelov) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:3342]: OK, thank you.
