### PR TITLE
Force mocking without mock framework installed fix

### LINKED ISSUE #190: Incorrect dependency path in code generator
**Description**

Dependency path is defined incorrectly and contains much more libraries than is actually installed.

**To Reproduce**

1) Run gradle task `runIde` from UtBot project 
2) Create new clean `Maven` project and add `Algorithms.Sort` class into it
3) Run tests generation for `quickSort` method with any test framework and `No mocks` setting.

**Expected behavior**

There is a special check that fails test generation process if there is no mock framework library. It is called `checkFrameworkDependencies`. We expect that this check will fail: as far as we did not install `mockito-core` somehow, this library is not present in the project. 

**Actual behavior**

This check passes because `dependencyPath` is defined incorrectly and contains `mockito-core` in it.

**Additional context**

The visual representation of this problem are:

1) uncompiled imports like `import static org.mockito.Mockito.when;`
2) test methods with errors like
```java
public void testQuickSort_errors() {
        // Couldn't generate some tests. List of errors:
        // 
        // 6 occurrences of:
        // org.mockito.MockedConstruction

    }
```

### PR DESCRIPTION
**Pull request by nikitavlaev**
# Description

Added mock listeners for engine to make it abstract from external events.
Added force mock listener.
Added url handler for urls like "#utbot/..." to launch configuration tasks from popups.
Added message with link to mock framework configuration to test reports if force mocking happened.

Fixes #190

## Type of Change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Manual Scenario 

Launched project without mockito installed.
Generated tests for Sort.quickSort without mocks -> mocks for Random were forced.
Checked that message suggesting mockito installation appeared in test report.
Verified that link in that message leads to the window for mockito configuration, and it installs correctly.
After installation, tests with force-mocks were generated correctly.

# Checklist (remove irrelevant options):

- [ ] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] Tests that prove my change is effective
- [ ] All tests pass locally with my changes

### CODE REVIEW

File: utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt [hunk 1]
```diff
@@ -2521,6 +2523,8 @@ class UtBotSymbolicEngine(
         )
     }
 
+    fun attachMockListener(mockListener: MockListener) = mocker.mockListenerController.attach(mockListener)
```
Comment (EgorkaKulikov) [inline utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt:2526]: Let's discuss why this code is a pat of engine, may be there is a very unclear relation here

File: utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/ForceMockListener.kt [hunk 2]
```diff
@@ -0,0 +1,23 @@
+package org.utbot.engine.util.mockListeners
+import org.utbot.engine.EngineController
+import org.utbot.engine.MockStrategy
+import org.utbot.engine.util.mockListeners.exceptions.ForceMockCancellationException
+
+/**
+ * Listener for mocker events in symbolic engine.
```
Comment (EgorkaKulikov) [inline utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/ForceMockListener.kt:7]: It is always better to mention entities in comments as named references like `[UtSymbolicEngine]`

File: utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/ForceMockListener.kt [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+ * If forced mock happened, cancels the engine job.
+ *
+ * Supposed to be created only if Mockito is not installed.
+ */
+class ForceMockListener: MockListener {
+    var forceMockHappened = false
```
Comment (EgorkaKulikov) [inline utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/ForceMockListener.kt:13]: Let's avoid public setter on it

File: utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/ForceMockListener.kt [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+
+    override fun onShouldMock(controller: EngineController, strategy: MockStrategy, shouldMock: Boolean) {
+        // If force mocking happened
+        if (shouldMock) {
+            // Cancel engine job
+            controller.job!!.cancel(ForceMockCancellationException())
```
Comment (EgorkaKulikov) [inline utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/ForceMockListener.kt:19]: I think that we would never like to crash here. Suggest to do like this
`controller.job?.let { ForceMockCancellationException() }`

File: utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/MockListenerController.kt [hunk 5]
```diff
@@ -0,0 +1,19 @@
+package org.utbot.engine.util.mockListeners
+
+import org.utbot.engine.EngineController
+import org.utbot.engine.MockStrategy
+
+/**
+ * Controller that allows to attach listeners to mocker in symbolic engine.
+ */
+class MockListenerController(private val controller: EngineController) {
+    val listeners = mutableListOf<MockListener>()
```
Comment (EgorkaKulikov) [inline utbot-framework/src/main/kotlin/org/utbot/engine/util/mockListeners/MockListenerController.kt:10]: What other listeners except `MockListener` may be in `MockListenerController`?

File: utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt [hunk 6]
```diff
@@ -6,16 +6,12 @@ import kotlinx.collections.immutable.persistentSetOf
 import kotlinx.collections.immutable.toPersistentList
 import kotlinx.collections.immutable.toPersistentMap
 import kotlinx.collections.immutable.toPersistentSet
-import kotlinx.coroutines.currentCoroutineContext
-import kotlinx.coroutines.CancellationException
-import kotlinx.coroutines.Job
+import kotlinx.coroutines.*
```
[the remark this answers is not in the document]
Comment (EgorkaKulikov) [reply utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt:9]: Check it in other files of this PR too, please

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/Notifications.kt [hunk 7]
```diff
@@ -95,5 +97,53 @@ object TestsReportNotifier : InformationUrlNotifier() {
...
+    }
+
+    private fun handleDescription(descriptionSuffix: String) {
+        when {
+            descriptionSuffix.startsWith(mockitoSuffix) -> {
+                project?.let { module?.let {
+                        if (createMockFrameworkNotificationDialog("Configure mock framework") == Messages.YES) {
+                            configureMockFramework(project!!, module!!)
+                        }
+                    } ?: error("Could not configure mock framework: null in module ")
```
Comment (EgorkaKulikov) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/Notifications.kt:143]: We need module or project name here: these message in logs will be just scaring

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/Notifications.kt [hunk 8]
```diff
@@ -95,5 +97,53 @@ object TestsReportNotifier : InformationUrlNotifier() {
...
+ */
+class TestReportUrlOpeningListener: NotificationListener.Adapter() {
+    companion object {
+        const val prefix = "#utbot/"
+        const val mockitoSuffix = "configure-mockito"
+    }
+    private val defaultListener = NotificationListener.UrlOpeningListener(false)
+
+    // Last project and module to be able to use them when activated for configuration tasks.
+    var project: Project? = null
```
[the remark this answers is not in the document]
Comment (EgorkaKulikov) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/Notifications.kt:123]: `configureMockFramework(project!!, module!!)` is very bad later

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/Notifications.kt [hunk 9]
```diff
@@ -95,5 +97,53 @@ object TestsReportNotifier : InformationUrlNotifier() {
...
+            handleDescription(description.removePrefix(prefix))
+        }
+        else {
+            return defaultListener.hyperlinkUpdate(notification, e)
+        }
+    }
+
+    private fun handleDescription(descriptionSuffix: String) {
+        when {
+            descriptionSuffix.startsWith(mockitoSuffix) -> {
```
Comment (EgorkaKulikov) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/Notifications.kt:138]: May be we should store a list of all possible suffixes and do smth like `when` here?

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/UtTestsDialogProcessor.kt [hunk 10]
```diff
@@ -175,6 +183,10 @@ object UtTestsDialogProcessor {
                                         testCasesByClass[srcClass] = notEmptyCases
                                     }
 
+                                    forceMockListener?.run {
+                                        model.forceMockingHappened = forceMockHappened
```
Comment (EgorkaKulikov) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/UtTestsDialogProcessor.kt:187]: Make the names similar, please

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/TestGenerator.kt [hunk 11]
```diff
@@ -320,6 +317,14 @@ object TestGenerator {
         val notifyMessage = buildString {
             appendHtmlLine(testsCodeWithTestReport.testsGenerationReport.toString())
             appendHtmlLine()
+            if (model.forceMockingHappened) {
```
Comment (EgorkaKulikov) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/TestGenerator.kt:320]: Actually it is not very scalable solution, but I'm not sure it is easy to do better.

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/Notifications.kt (hunk 8 above)
[the remark this answers is not in the document]
Comment (nikitavlaev) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/Notifications.kt:123]: Yes, they should really be nullable. The other approach is to use `lateinit var`, but this will cause tight coupling with `TestReportNotifier` and force initialization of such properties at some point in the caller code, which is not obvious.

**Review by EgorkaKulikov — APPROVED** [review]

**Comment by EgorkaKulikov** [comment]
Approve in accordance with our verbal discussion on improvements

**Review by CaelmBleidd — APPROVED** [review]
There is an odd-looking connection between the mocker, its controllers, engine controllers and listeners. Seems like it is a problem with the design and it might cause further problems with engine refactorings and separation of the virtual machine and traverse

Approved since the PR contains required fix and need to be tested ASAP
