### PR TITLE
Minor refactoring in SimpleCommentBuildr and CustomJavaDocCommentBuilder

### LINKED ISSUE #787: Refactor SimpleCommentBuilder and CustomJavaDocCommentBuilder
**Description**

There are expressions that are always null in `SimpleCommentBuilder#buildThrownExceptionInfo()` line 49 and `CustomJavaDocCommentBuilder#buildCustomJavaDocComment()` line 62.

### PR DESCRIPTION
**Pull request by onewhl**
# Description

There are expressions that are always null in `SimpleCommentBuilder#buildThrownExceptionInfo()` line 49 and `CustomJavaDocCommentBuilder#buildCustomJavaDocComment() ` line 62.
This PR contains minor refactoring of these methods. 

Fixes #787

## Type of Change

Please delete options that are not relevant.

- Minor bug fix (non-breaking small changes)

# How Has This Been Tested?

Run tests in summaries-test.

## Automated Testing

Run tests in summaries-test.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] New tests have been added
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt [hunk 1]
```diff
@@ -45,16 +45,14 @@ class CustomJavaDocCommentBuilder(
...
             val exceptionName = thrownException.javaClass.name
             val reason = findExceptionReason(currentMethod, thrownException)
             "{@link $exceptionName} $reason"
         }
 
-        if (exceptionThrow != null) {
-            customJavaDocComment.throwsException = exceptionThrow
+        if (thrownExceptionDescription != null) {
+            customJavaDocComment.throwsException = thrownExceptionDescription
         }
```
Comment (Damtev) [inline utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt:56]: I guess, it could be a little simplified:

```kotlin
if (thrownException != null) {
    val exceptionName = thrownException.javaClass.name
    val reason = findExceptionReason(currentMethod, thrownException)

    customJavaDocComment.throwsException = "{@link $exceptionName} $reason"
}
```

**Review by Damtev — CHANGES_REQUESTED** [review]

File: utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt (hunk 1 above)
Comment (onewhl) [reply utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt]: I agree, thanks!

**Review by Damtev — APPROVED** [review]
