### PR TITLE
Disabled tests for autogenerated functions #457

### LINKED ISSUE #457: Unexpected tests for valueOf on enums
**Description**

Generated tests for enum contain methods testing valueOf

**To Reproduce**

1. Run Contest Estimator with method `com.google.common.base.CaseFormat.*` and 300s time limit.

**Actual behavior**

Generated tests contain the following:
```java
    @Test
    //@org.junit.jupiter.api.DisplayName("valueOf: arg_0 = blank string -> throw IllegalArgumentException")
    public void testValueOfThrowsIAEWithBlankString() {
        /* This test fails because executable under testing com.google.common.base.CaseFormat.valueOf
        produces Runtime exception java.lang.IllegalArgumentException: No enum constant com.google.common.base.CaseFormat.    */
        CaseFormat.valueOf("   ");
    }

    @Test
    //@org.junit.jupiter.api.DisplayName("valueOf: arg_0 has special characters -> throw IllegalArgumentException")
    public void testValueOfThrowsIAEWithBlankString1() {
        /* This test fails because executable under testing com.google.common.base.CaseFormat.valueOf
        produces Runtime exception java.lang.IllegalArgumentException: No enum constant com.google.common.base.CaseFormat.
	
 */
        CaseFormat.valueOf("\n\t\r");
    }
```

### PR DESCRIPTION
**Pull request by volivan239**
# Description

Disabled tests for autogenerated methods (values, valueOf) for enum classes.
Fixes #457

## Type of Change

-  Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Automated Testing

No new tests currently added (in progress)

## Manual Scenario 

* Launch plugin on empty enum class -- it will suppose no methods to generate test, as expected
* Launch contest estimator on `com.google.common.base.CaseFormat.*` -- it will no more generate tests for `values` and `valueOf`.

# Checklist (remove irrelevant options):

- [ ] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] Tests that prove my change is effective
- [ ] All tests pass locally with my changes

### CODE REVIEW

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/UtTestsDialogProcessor.kt [hunk 1]
```diff
@@ -127,8 +127,13 @@ object UtTestsDialogProcessor {
                             for (srcClass in model.srcClasses) {
                                 val methods = ReadAction.nonBlocking<List<UtMethod<*>>> {
                                     val clazz = classLoader.loadClass(srcClass.qualifiedName).kotlin
+                                    val allMethods = TestIntegrationUtils.extractClassMethods(srcClass, false)
                                     val srcMethods = model.selectedMethods?.toList() ?:
-                                        TestIntegrationUtils.extractClassMethods(srcClass, false)
+                                        if (!srcClass.isEnum)
```
Comment (dtim) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/UtTestsDialogProcessor.kt:132]: It seems that the approach with `SyntheticElement` can be used here as well.

File: utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt [hunk 2]
```diff
@@ -472,6 +473,9 @@ private fun prepareClass(kotlinClass: KClass<*>, methodNameFilter: String?): Lis
         .filterNot {
             it.isConstructor && (it.clazz.isAbstract || it.clazz.java.isEnum)
         }
+        .filterNot {
+            it.displayName.substringBefore('(') in listOf("values", "valueOf") && it.clazz.java.isEnum
```
Comment (dtim) [inline utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt:477]: There are many sequential calls to `filter`/`filterNot`. To avoid creation of too many intermediate lists, it would be better to use `asSequence()` call on the original collection (`methodsToGenerate`), and then convert the resulting  sequence to a list.

File: utbot-cli/src/main/kotlin/org/utbot/cli/GenerateTestsCommand.kt [hunk 3]
```diff
@@ -91,7 +92,11 @@ class GenerateTestsCommand :
             logger.debug { "Classpath to be used: ${newline()} $classPath ${newline()}" }
 
             val classUnderTest: KClass<*> = loadClassBySpecifiedFqn(targetClassFqn)
-            val targetMethods = classUnderTest.targetMethods()
+            val targetMethods = if (!classUnderTest.java.isEnum)
+                classUnderTest.targetMethods()
+                else classUnderTest.targetMethods().filterNot {
+                    it.displayName.substringBefore('(') in listOf("values", "valueOf")
```
Comment (dtim) [inline utbot-cli/src/main/kotlin/org/utbot/cli/GenerateTestsCommand.kt:98]: I think that string constants should be defined once, e.g., in an object in `utbot-framework-api`, and referenced everywhere they are needed: cli, contest estimator, maybe the plugin (see next comments for details about the plugin).

Maybe the condition that is used inside `filterNot` may be implemented as a separate function as well?

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt [hunk 4]
```diff
@@ -345,7 +345,10 @@ class GenerateTestsDialogWindow(val model: GenerateTestsModel) : DialogWrapper(m
 
         val items: List<MemberInfo>
         if (srcClasses.size == 1) {
-            items = TestIntegrationUtils.extractClassMethods(srcClasses.single(), false)
+            val allMethods = TestIntegrationUtils.extractClassMethods(srcClasses.single(), false)
+            items = if (!srcClasses.single().isEnum)
```
[the remark this answers is not in the document]
Comment (volivan239) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt]: Rewrote like you suggested, the code looks prettier now

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/UtTestsDialogProcessor.kt (hunk 1 above)
Comment (volivan239) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/UtTestsDialogProcessor.kt]: done

File: utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt (hunk 2 above)
Comment (volivan239) [reply utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt]: done, but I have no idea what is the best way to deal with many sequential filters

File: utbot-cli/src/main/kotlin/org/utbot/cli/GenerateTestsCommand.kt (hunk 3 above)
Comment (volivan239) [reply utbot-cli/src/main/kotlin/org/utbot/cli/GenerateTestsCommand.kt]: Put list of excluded methods into `org.utbot.framework.SyntheticMethods` and moved condition in filter to a function in `org.utbot.framework.util` (`SyntheticMethodsChecker.kt`)

File: utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntethicMethodsChecker.kt [hunk 5]
```diff
@@ -0,0 +1,8 @@
+package org.utbot.framework.util
+
+import org.utbot.engine.displayName
+import org.utbot.framework.SyntheticMethods
+import org.utbot.framework.plugin.api.UtMethod
+
+fun isSynthetic(method: UtMethod<*>): Boolean =
```
Comment (dtim) [inline utbot-framework/src/main/kotlin/org/utbot/framework/util/SyntethicMethodsChecker.kt:7]: We already have an extension function for `ClassId` with the same name that checks the corresponding JVM attribute of the method: `org.utbot.framework.plugin.api.ClassId#isSynthetic`.

Your function applies to enums only, so I think it would be better to rename it.

I would also suggest to avoid creating Kotlin files with a single function. It seems that this function can be moved to `SyntheticMethods.kt`, it would be easier to navigate the code that way.

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt [hunk 6]
```diff
@@ -0,0 +1,5 @@
+package org.utbot.framework
+
+object SyntheticMethods {
```
Comment (dtim) [inline utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt:3]: This objects stores method names, not `UtMethod` or Java/Kotlin callables, so I would suggest to rename it to something like "KnownSyntheticMethodNames".

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt [hunk 7]
```diff
@@ -0,0 +1,5 @@
...
+    val enumSyntheticMethods = listOf("values", "valueOf")
```
Comment (dtim) [inline utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt:4]: I think it would be nice to have a KDoc for `enumSyntheticMethods` value and for the container object.

File: utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt [hunk 8]
```diff
@@ -466,12 +468,13 @@ private fun prepareClass(kotlinClass: KClass<*>, methodNameFilter: String?): Lis
...
         .union(kotlin2javaCtors)
 
-    val classFilteredMethods = methodsToGenerate
+    val classFilteredMethods = methodsToGenerate.asSequence()
         .map { UtMethod(it.first, kotlinClass) }
         .filter { methodNameFilter?.equals(it.callable.name) ?: true }
         .filterNot {
             it.isConstructor && (it.clazz.isAbstract || it.clazz.java.isEnum)
-        }
+        }.filterWhen(!UtSettings.generateForSyntheticMethods) { !isSynthetic(it) }
```
Comment (dtim) [inline utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt:476]: I would suggest to write `filterNot` condition in a single line, or at least move `.filterWhen` call to the next line after the closing brace.

**Review by dtim — CHANGES_REQUESTED** [review]
Algorithmically and conceptually the PR is good, but there are some issues with the code organization. I would like also suggest some stylistic changes.

File: utbot-core/src/main/kotlin/org/utbot/common/FilterWhen.kt [hunk 9]
```diff
@@ -0,0 +1,21 @@
+package org.utbot.common
+
+/**
+ * If [condition] is true, returns list containing only elements, matching [predicate].
```
Comment (dtim) [inline utbot-core/src/main/kotlin/org/utbot/common/FilterWhen.kt:4]: I think an article is missing before "list", and a comma before "matching" is not necessary: "If [condition] is true, returns a list containing only elements matching [predicate]".

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt [hunk 10]
```diff
@@ -375,6 +375,11 @@ object UtSettings {
      */
     var singleSelector by getBooleanProperty(true)
 
+    /**
+     * Flag that indicates whether tests for synthetic methods (values, valueOf in enums) should be generated, or not
+     */
+    var generateForSyntheticMethods by getBooleanProperty(false)
```
[the remark this answers is not in the document]
Comment (volivan239) [reply utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt]: Renamed to `skipTestGenerationForSyntheticMethods` with opposite value

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt (hunk 6 above)
Comment (volivan239) [reply utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt]: Renamed to `KnownSyntheticMethodNames`

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt (hunk 7 above)
Comment (volivan239) [reply utbot-framework-api/src/main/kotlin/org/utbot/framework/SyntheticMethods.kt]: Done

File: utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt (hunk 8 above)
Comment (volivan239) [reply utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt]: Done

**Review by dtim — APPROVED** [review]
LGTM. If possible, it would be nice to have some unit tests in CLI.
