### PR TITLE
Fix incomplete results in the SARIF report

### LINKED ISSUE #460: Incorrect region in SARIF report
**Description**

Sometimes we have such region in SARIF report:
```JSON
"region" : {
    "startLine" : 1,
    "startColumn" : 1
}
```

But the first line of the source code contains the package name or class name. So there can't be an unchecked exception there.

**To Reproduce**

1. Run test generation using IDEA plugin:
```Java
public class Util {
    public static int multiply(int x, int y) {
        return Math.multiplyExact(x, y);
    }
}
```
2. Open generated SARIF report
3. Find the incorrect region

**Expected behavior**

The SARIF report contains only correct regions.

**Visual proofs**

image

### PR DESCRIPTION
**Pull request by IdeaSeeker**
# Description

- Fixed incorrect highlighted region
- Fixed incomplete analysis steps

Fixes #460, #470

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Manual Scenario

1. Run test generation using IDEA plugin
2. Check the created SARIF report. All results should:
  - refer to the correct line in the source code:
  image
  - have the correct `Generated test for this case` link:
  image
  - have at least 2 (correct) _Analysis steps_: from the test method and from the source method:
  image

# Checklist:

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-framework/src/main/kotlin/org/utbot/sarif/SarifReport.kt [hunk 1]
```diff
@@ -301,10 +298,24 @@ class SarifReport(
         return "..."
     }
 
-    private fun extractLineNumber(utExecution: UtExecution): Int? =
-        try {
+    /**
+     * Returns the number of the last line in the execution path.
+     */
+    private fun getLastLineNumber(utExecution: UtExecution): Int? {
```
Comment (nikitavlaev) [inline utbot-framework/src/main/kotlin/org/utbot/sarif/SarifReport.kt:304]: maybe like 
```
        try {
            utExecution.path.lastOrNull()?.stmt?.javaSourceStartLineNumber
        } catch (t: Throwable) {
            // if for some reason we can't extract the last line from the path
            // return last covered instruction
            utExecution.coverage?.coveredInstructions?.lastOrNull()?.lineNumber
        }
```

**Review by nikitavlaev — APPROVED** [review]
