### PR TITLE
Fixed the weird logic in the of error messages in SummaryTestCaseGeneratorTest #383

### LINKED ISSUE #383: Wrong logic of error messages in List<UtExecution>.checkMatchersWithDisplayNames
**Description**

List<UtExecution>.checkMatchersWithDisplayNames and other checkers prints summaries if something goes wrong like here:

` Assertions.assertTrue(notMatchedExecutions.isEmpty()) { "Not matched display names ${summaries(notMatchedExecutions)}" }`

**To Reproduce**

Run the test in utbot-summary with the error test data

**Expected behavior**

You obtain correct and clear message what's exactly wrong and what part of summaries is missed

**Actual behavior**

It prints comments in all cases (not matched display names, not matched test names and not matched comments)

### PR DESCRIPTION
**Pull request by amandelpie**
# Description

This PR covers more cases with matching of generated and provided in tests display names, method names and comments
Also, now it prints what's exactly happens and formatted it well.

Also, this ticket is required to start the following ticket #382 

Fixes #383

## Type of Change

Please delete options that are not relevant.

- Refactoring (typos and non-functional changes) 

# How Has This Been Tested?

## Manual Scenario 

Just change something in the tests data for the utbot-summary-test module and you will obtain the formatted well messages.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [x] New tests have been added
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-summary-tests/src/test/kotlin/examples/SummaryTestCaseGeneratorTest.kt [hunk 1]
```diff
@@ -120,18 +124,51 @@ open class SummaryTestCaseGeneratorTest(
...
+                val normalize = execution.summary?.toString()?.normalize()
+                normalize?.contains(comment.normalize()) == true
+            }
+        }
+
+        Assertions.assertTrue(notMatchedExecutions.isEmpty() && notMatchedComments.isEmpty()) {
+            buildString {
+                if (notMatchedExecutions.isNotEmpty()) {
+                    append(
+                        "\nThe following comments were produced by the UTBot, " +
```
Comment (onewhl) [inline utbot-summary-tests/src/test/kotlin/examples/SummaryTestCaseGeneratorTest.kt:151]: Maybe we can mark it as actual value somehow? I mean it could make the message more clear.

File: utbot-summary-tests/src/test/kotlin/examples/SummaryTestCaseGeneratorTest.kt [hunk 2]
```diff
@@ -120,18 +124,51 @@ open class SummaryTestCaseGeneratorTest(
...
+                                    commentsFromExecutions(
+                                        notMatchedExecutions
+                                    )
+                                }"
+                    )
+                }
+
+                if (notMatchedComments.isNotEmpty()) {
+                    append(
+                        "\nThe following comments were passed in the check() method, " +
```
Comment (onewhl) [inline utbot-summary-tests/src/test/kotlin/examples/SummaryTestCaseGeneratorTest.kt:162]: And here is expected value

**Review by onewhl — COMMENTED** [review]
Now output looks more clear, thank you!
I have only one suggestion -- to mark the expected and actual values explicitly.

File: utbot-summary-tests/src/test/kotlin/math/SummaryOfMathTest.kt [hunk 3]
```diff
@@ -143,13 +143,13 @@ class SummaryOfMathTest : SummaryTestCaseGeneratorTest(
                 "Test then returns from: return acummulator.snapshot();\n"
         val summary6 = "Test calls {@link guava.examples.math.StatsAccumulator#addAll(double[])},\n" +
                 "    there it iterates the loop for(double value: values) twice,\n" +
-                "        inside this loop, the test calls StatsAccumulator::add,\n" +
+                "        inside this loop, the test calls {@link guava.examples.math.StatsAccumulator#add(double)},\n" +
                 "        there it executes conditions:\n" +
                 "            (!isFinite(value)): True\n" +
-                "Test afterwards calls {@link guava.examples.math.StatsAccumulator#snapshot()},\n" +
+                "Test then calls {@link guava.examples.math.StatsAccumulator#snapshot()},\n" +
```
[the remark this answers is not in the document]
Comment (amandelpie) [reply utbot-summary-tests/src/test/kotlin/math/SummaryOfMathTest.kt:149]: Unfortunately, no. the order of the produced tests is not guaranteed

File: utbot-summary-tests/src/test/kotlin/examples/SummaryTestCaseGeneratorTest.kt (hunk 1 above)
Comment (amandelpie) [reply utbot-summary-tests/src/test/kotlin/examples/SummaryTestCaseGeneratorTest.kt:151]: Unfortunately, no. the order of the produced tests is not guaranteed

File: utbot-summary-tests/src/test/kotlin/examples/SummaryTestCaseGeneratorTest.kt (hunk 2 above)
Comment (amandelpie) [reply utbot-summary-tests/src/test/kotlin/examples/SummaryTestCaseGeneratorTest.kt:162]: Unfortunately, no. the order of the produced tests is not guaranteed

**Review by onewhl — APPROVED** [review]
Looks good to me!
