### PR TITLE
IDE fatal error during tests generation #68

### LINKED ISSUE #68: IDE fatal error during tests generation
**Description**

IDE fatal error occured during tests generation. The stack trace of this error is represented on the attached screenshot.

**To Reproduce**

Unfortunately, this problem is flacky.

Exception stack trace is 

```
Freeze in EDT for 21 seconds
Sampled time: 14900ms, sampling rate: 100ms, GC time: 194ms (1%), Class loading: 6%

com.intellij.diagnostic.Freeze
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.functionAdditionalResolve(ResolveElementCache.kt:678)
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.performElementAdditionalResolve(ResolveElementCache.kt:397)
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.getElementsAdditionalResolve(ResolveElementCache.kt:225)
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.resolveToElements(ResolveElementCache.kt:284)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl$analyze$3.invoke(ModuleResolutionFacadeImpl.kt:74)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl$analyze$3.invoke(ModuleResolutionFacadeImpl.kt:41)
	at com.intellij.openapi.progress.impl.CancellationCheck.withCancellationCheck(CancellationCheck.kt:48)
	at com.intellij.openapi.progress.impl.CancellationCheck$Companion.runWithCancellationCheck(CancellationCheck.kt:80)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runWithCancellationCheck(ApplicationUtils.kt:46)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl.analyze(ModuleResolutionFacadeImpl.kt:73)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeWithDebugInfo.analyze(ResolutionFacadeWithDebugInfo.kt:51)
	at org.jetbrains.kotlin.idea.core.ShortenReferences$shortenReferencesInFile$$inlined$runReadAction$2$lambda$1.invoke(ShortenReferences.kt:231)
	at org.jetbrains.kotlin.idea.core.ShortenReferences$shortenReferencesInFile$$inlined$runReadAction$2$lambda$1.invoke(ShortenReferences.kt:42)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolveInDispatchThreadManagerKt.allowResolveInDispatchThread(ResolveInDispatchThreadManager.kt:132)
	at org.jetbrains.kotlin.idea.core.ShortenReferences$shortenReferencesInFile$$inlined$runReadAction$2.compute(actions.kt:82)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:851)
	at org.jetbrains.kotlin.idea.core.ShortenReferences.shortenReferencesInFile(ShortenReferences.kt:801)
	at org.jetbrains.kotlin.idea.core.ShortenReferences.process(ShortenReferences.kt:181)
	at org.jetbrains.kotlin.idea.core.ShortenReferences.process(ShortenReferences.kt:103)
	at org.jetbrains.kotlin.idea.core.ShortenReferences.process(ShortenReferences.kt:111)
	at org.jetbrains.kotlin.idea.core.ShortenReferences.process$default(ShortenReferences.kt:109)
	at org.utbot.intellij.plugin.generator.TestGenerator.reformat(TestGenerator.kt:251)
	at org.utbot.intellij.plugin.generator.TestGenerator.addTestMethodsAndSaveReports(TestGenerator.kt:208)
	at org.utbot.intellij.plugin.generator.TestGenerator.generateTestsInternal(TestGenerator.kt:88)

```

**Visual proofs (screenshots, logs, images)**

image

### PR DESCRIPTION
**Pull request by Vassiliy-Kudryashov**
# Description

Long activity in EDT+WriteAction was split into parts  long activities run on pooled threads and WriteAction is used only were we need it (mostly ReadAction is enough)

Fixes #68

## Type of Change

- Bug fix (non-breaking change which fixes an issue)
# How Has This Been Tested?
## Manual Scenario 

Run test generation on a package. IDEA freeze report shouldn't appear.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] No new warnings

### CODE REVIEW

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/TestGenerator.kt [hunk 1]
```diff
@@ -44,39 +46,62 @@ import com.intellij.psi.codeStyle.JavaCodeStyleManager
...
-    fun generateTests(model: GenerateTestsModel, testCases: Map<PsiClass, List<UtTestCase>>) {
-        runWriteCommandAction(model.project, "Generate tests with UtBot", null, {
-            generateTestsInternal(model, testCases)
-        })
+    private enum class Target {THREAD_POOL, READ_ACTION, WRITE_ACTION, EDT_LATER}
+
+    private fun run(target: Target, runnable: Runnable) {
+        UtContext.currentContext()?.let {
+            when (target) {
+                THREAD_POOL -> AppExecutorUtil.getAppExecutorService().submit{
```
Comment (Markoutte) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/TestGenerator.kt:88]: space missed after in `submit{`

**Review by Markoutte — COMMENTED** [review]
There's possible situation when latch will hang the thread because it is not guaranteed that latch is counted down in every possible way. Right now it is a minor problem, because looks like it works, but can be very hidden problem in the future.

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/TestGenerator.kt (hunk 1 above)
Comment (Vassiliy-Kudryashov) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/TestGenerator.kt:88]: fixed

**Review by denis-fokin — APPROVED** [review]
