### PR TITLE
Fix unwanted fields in test class for Spring

### LINKED ISSUE #2170: Unexpected @Mock for Collection in Spring Controller tests
**Description**

Unexpected @Mock for Collection and Page in Spring Controller tests.

collectionMock is never used

**To Reproduce**

1. Install [UnitTestBot plugin built from main](https://github.com/UnitTestBot/UTBotJava/actions/runs/4743615007) in IntelliJ IDEA
2. Open `spring-petclinic` project
3. Generate tests for `VetController`

**Expected behavior**

There should be fields annotated with `@Mock` for the used beans only.

**Actual behavior**

There are additional fields annotated with `@Mock` for `java.util.Collection` and `org.springframework.data.domain.Page`
collectionMock is never used.
pageMock is used in 1 error-prone test.

**Screenshots, logs**

~~~java
import org.mockito.Mock;
import java.util.Collection;
import org.springframework.data.domain.Page;
import java.util.List;

public final class VetControllerTest {
	@InjectMocks
	public VetController vetController;

	@Mock
	public VetRepository vetRepositoryMock;

	@Mock
	public Collection collectionMock;

	@Mock
	public Page pageMock;

	public AutoCloseable mockitoCloseable;
...
}
~~~

Mocks of Page is used in the following test:

~~~java
	///region OTHER: ERROR SUITE for method showVetList(int, org.springframework.ui.Model)

	@Test
	public void testShowVetList1() {
		org.mockito.MockedConstruction mockedConstruction = null;
		org.mockito.MockedStatic mockedStatic = null;
		try {
			ArrayList arrayList = new ArrayList();
			arrayList.add(null);
			arrayList.add(null);
			arrayList.add(null);
			arrayList.add(null);
			arrayList.add(null);
			arrayList.add(null);
			mockedConstruction = mockConstruction(Vets.class, (Vets vetsMock, org.mockito.MockedConstruction.Context context) -> (when(vetsMock.getVetList())).thenReturn(arrayList));
			mockedStatic = mockStatic(PageRequest.class);
			(mockedStatic.when(() -> PageRequest.of(anyInt(), anyInt()))).thenReturn(((PageRequest) null));
			ArrayList arrayList1 = new ArrayList();
			arrayList1.add(null);
			arrayList1.add(null);
			arrayList1.add(null);
			(when(pageMock.toList())).thenReturn(arrayList1);
			(when(vetRepositoryMock.findAll(any()))).thenReturn(pageMock);
			Model modelMock = mock(Model.class);

            /* This test fails because method [org.springframework.samples.petclinic.vet.VetController.showVetList] produces [org.mockito.exceptions.base.MockitoException: \nCannot call abstract real method on java object!\nCalling real methods is only possible when mocking non abstract method.\n  //correct example:\n  when(mockOfConcreteClass.nonAbstractMethod()).thenCallRealMethod();]
                org.utbot.instrumentation.instrumentation.execution.constructors.MockValueConstructor$generateMockitoAnswer$1.answer(MockValueConstructor.kt:178)
                org.springframework.samples.petclinic.vet.VetController.addPaginationModel(VetController.java:56)
                org.springframework.samples.petclinic.vet.VetController.showVetList(VetController.java:51) */
			vetController.showVetList(0, modelMock);
		} finally {
			mockedConstruction.close();
			mockedStatic.close();
		}
	}
	///endregion
~~~

**Environment**

IntelliJ IDEA version - 2023.1 Ultimate
Project - opened as Maven
JDK - 17

### PR DESCRIPTION
**Pull request by sofurihafe**
## Description

There were unwanted fields with **@Mock** annotation because we were collecting everything from models, including fields and mocks. But there is no need for collecting mocks, they will be created when necessary.

Fixes #2170

### Manual tests

Reproduced the issue from the issue and on the OwnerController class.

### CODE REVIEW

File: utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt [hunk 1]
```diff
@@ -102,7 +102,6 @@ class SpringTestClassModelBuilder(val context: CgContext): TestClassModelBuilder
             }
             is UtCompositeModel -> {
                 currentModel.fields.values.forEach { collectRecursively(it, allModels) }
-                currentModel.mocks.values.asSequence().flatten().forEach { collectRecursively(it, allModels) }
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt:105]: It definitely requires a comment with an explanation of why we do NOT need to collect models from mocks

**Review by Damtev — APPROVED** [review]
Overall, LGTM, but need some comments explicitly in the code

File: utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt (hunk 1 above)
Comment (EgorkaKulikov) [reply utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt:105]: Strongly agree.

**Review by EgorkaKulikov — APPROVED** [review]

File: utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt (hunk 1 above)
Comment (sofurihafe) [reply utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt:105]: Done.
