### PR TITLE
Overflow in fuzzing #588

### LINKED ISSUE #588: Overflow in fuzzing
**Description**

There is problem with negative size in Combinations. This is cause of crash UtBot.

**To Reproduce**

Run ContestEstimator on project antlr, class org.antlr.v4.parse.LeftRecursiveRuleWalker.

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

ContestEstimator crashes with exception from fuzz function.

**Visual proofs (screenshots, logs, images)**

~~~
Exception in thread "SymbolicExecution" java.lang.IllegalStateException: Size must be positive or 0 but current value is -1810579852
	at org.utbot.fuzzer.PseudoShuffledIntProgression.<init>(PseudoShuffledIntProgression.kt:95)
	at org.utbot.fuzzer.PseudoShuffledIntProgression.<init>(PseudoShuffledIntProgression.kt:89)
	at org.utbot.fuzzer.CartesianProduct.iterator(CartesianProduct.kt:18)
	at org.utbot.fuzzer.CartesianProduct.asSequence(CartesianProduct.kt:13)
	at org.utbot.fuzzer.FuzzerKt.fuzz(Fuzzer.kt:34)
	at org.utbot.fuzzer.providers.ObjectModelProvider.generateModelsWithFieldsInitialization(ObjectModelProvider.kt:119)
	at org.utbot.fuzzer.providers.ObjectModelProvider.access$generateModelsWithFieldsInitialization(ObjectModelProvider.kt:37)
	at org.utbot.fuzzer.providers.ObjectModelProvider$generate$1.invokeSuspend(ObjectModelProvider.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at org.utbot.fuzzer.ModelProvider$Combined$generate$1.invokeSuspend(ModelProvider.kt:143)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at org.utbot.fuzzer.FuzzerKt.fuzz(Fuzzer.kt:76)
	at org.utbot.fuzzer.providers.ObjectModelProvider$Companion.fuzzParameters(ObjectModelProvider.kt:173)
	at org.utbot.fuzzer.providers.ObjectModelProvider$Companion.access$fuzzParameters(ObjectModelProvider.kt:145)
	at org.utbot.fuzzer.providers.ObjectModelProvider$generate$1.invokeSuspend(ObjectModelProvider.kt:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at org.utbot.fuzzer.ModelProvider$withFallback$1$1.invokeSuspend(ModelProvider.kt:142)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at kotlin.sequences.TakeSequence$iterator$1.hasNext(Sequences.kt:421)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:752)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:782)
	at kotlin.sequences.SequencesKt__SequencesKt$shuffled$1.invokeSuspend(Sequences.kt:140)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:110)
	at org.utbot.engine.UtBotSymbolicEngine$fuzzing$2.invokeSuspend(UtBotSymbolicEngine.kt:406)
	at org.utbot.engine.UtBotSymbolicEngine$fuzzing$2.invoke(UtBotSymbolicEngine.kt)
	...
~~~

**Environment**

Java 8.

### PR DESCRIPTION
**Pull request by Markoutte**
# Description

Overflow occurs in randomizer when fuzzing tries to shuffle values for further processing. The solution is to divide PseudoShuffledIntProgression into parts which can be processed within range 0..Int.MAX_VALUE. It decreases level of how random combinations are, but this is a little trade-off between memory consumption and this level.

Also, CombinationsKt is changed to process up to Long.MAX_VALUE combinations.

Fixes #588

## Type of Change

Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Automated Testing

org.utbot.framework.plugin.api.CombinationsTest
org.utbot.framework.plugin.api.FuzzerTest

## Manual Scenario 

Verify the origin problem from #588

# Checklist:

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [x] No new warnings
- [x] New tests have been added
- [ ] All tests pass locally with my changes

### CODE REVIEW

File: utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/Combinations.kt [hunk 1]
```diff
@@ -63,18 +63,21 @@ class Combinations(vararg elementNumbers: Int): Iterable<IntArray> {
...
 
     init {
         val badValue = elementNumbers.indexOfFirst { it <= 0 }
         if (badValue >= 0) {
             throw IllegalArgumentException("Max value must be at least 1 to build combinations, but ${elementNumbers[badValue]} is found at position $badValue (list: $elementNumbers)")
         }
-        count = IntArray(elementNumbers.size) { elementNumbers[it] }
+        count = LongArray(elementNumbers.size) { elementNumbers[it].toLong() }
         for (i in count.size - 2 downTo 0) {
             count[i] = count[i] * count[i + 1]
```
Comment (SBOne-Kenobi) [inline utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/Combinations.kt:77]: Math.multiplyExact looks better

**Review by SBOne-Kenobi — CHANGES_REQUESTED** [review]

**Review by SBOne-Kenobi — APPROVED** [review]
LGTM
