### PR TITLE
Fixed test generation for paths with spaces in JavaScript

### LINKED ISSUE #1586: No JS tests are generated when project path has spaces
**Description**

In case path to project contains whitespaces then either exception thrown or silently no tests are generated.

**To Reproduce**

1. Create simple JS -> HTML5 Bolierplate project in folder with spaces. For example path to my project is `C:\Users\t00814305\IdeaProjects\Release Dec 22\JS1\`
2. Try to generate tests

**Expected behavior**

Tests are generated

**Actual behavior**

For the first generation after project opened exception thrown and no test are generated. Then just no test generated without any error shown or presented in the log.

**Visual proofs (screenshots, logs, images)**
Exception thrown:
```
2022-12-26 10:56:06,764 [ 366824] SEVERE - #c.i.o.p.Task - C:\Users\t00814305\IdeaProjects\Release Dec 22\JS1\utbotJs\tempBase.json (The system cannot find the file specified)
java.io.FileNotFoundException: C:\Users\t00814305\IdeaProjects\Release Dec 22\JS1\utbotJs\tempBase.json (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at service.FastCoverageService.getBaseCoverage(FastCoverageService.kt:80)
	at service.FastCoverageService.<init>(FastCoverageService.kt:53)
	at service.CoverageServiceProvider.runFastCoverageAnalysis(CoverageServiceProvider.kt:89)
	at service.CoverageServiceProvider.get(CoverageServiceProvider.kt:30)
	at api.JsTestGenerator.makeTestsForMethod(JsTestGenerator.kt:129)
	at api.JsTestGenerator.run(JsTestGenerator.kt:104)
	at org.utbot.intellij.plugin.language.js.JsDialogProcessor$createTests$1.run(JsDialogProcessor.kt:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by zishkaz**
# Description

Now UTBot JavaScript supports test generation for files and directories with spaces in their paths.

Fixes #1586

## Type of Change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Manually

## Manual Scenario 
* Create directory with spaces in its name.
* Place a JavaScript file there and run test generation.
* Tests are generated.

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] No new warnings
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-intellij-js/src/main/kotlin/org/utbot/intellij/plugin/language/js/JsDialogProcessor.kt [hunk 1]
```diff
@@ -102,25 +102,25 @@ object JsDialogProcessor {
...
+                    .interpreters.first().interpreterSystemIndependentPath
+                val (_, error) = JsCmdExec.runCommand(
+                    shouldWait = true,
+                    cmd = arrayOf("\"${jsTestsModel.pathToNode}\"", "-v")
+                )
+                if (error.readText().isNotEmpty()) throw NoSuchElementException()
+                JsDialogWindow(it)
+            } catch (e: NoSuchElementException) {
+                Messages.showErrorDialog(
+                    "Node.js interpreter is not found in IDEA settings.\n" +
```
Comment (denis-fokin) [inline utbot-intellij-js/src/main/kotlin/org/utbot/intellij/plugin/language/js/JsDialogProcessor.kt:117]: Do kotlin multiline strings with trim work here?

**Review by Markoutte — CHANGES_REQUESTED** [review]
Cannot run action to generate test on Windows because of error:

```
java.io.IOException: Cannot run program ""npm"" (in directory "D:\Developer\untitled-js"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at utils.JsCmdExec.runCommand(JsCmdExec.kt:21)
	at org.utbot.intellij.plugin.language.js.UtilsKt.npmListByFlag(Utils.kt:26)
	at org.utbot.intellij.plugin.language.js.UtilsKt.findFrameworkLibrary(Utils.kt:38)
	at org.utbot.intellij.plugin.language.js.UtilsKt.getFrameworkLibraryPath(Utils.kt:18)
	at org.utbot.intellij.plugin.language.js.JsDialogProcessor$createDialogAndGenerateTests$1$run$$inlined$invokeLater$1.run(ApplicationUtils.kt:94)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 37 more
```

**Review by Markoutte — APPROVED** [review]
