### PR TITLE
Plugin setting to choose Kotlin generation doesn't work #1075

### LINKED ISSUE #1075: Plugin setting to choose Kotlin generation doesn't work
**Description**

Running plugin, we have settings for `UnitTestBot`. One of them is `Generated test language` - `Java` by default, with an experimental `Kotlin` option. But this option does not work, and it is impossible to generate a test in `Kotlin` language.

**To Reproduce**

1. Use `runIde` task and open any Java project
2. Set `Generated test language` to `Kotlin (experimental)`
3. Run test generation action with any options for any method

**Expected behavior**

Kotlin test file is supposed to be generated (maybe uncompiled, but existed).

**Actual behavior**

Java test file is generated, and `Generated test language` is reset to `Java`.

### PR DESCRIPTION
**Pull request by Vassiliy-Kudryashov**
# Description

Actual codegen language should depend on settings only

Fixes #1075 

## Type of Change

- Bug fix (non-breaking change which fixes an issue)
# How Has This Been Tested?

## Manual Scenario 

See the issue, generation output has to be exactly the same as it defined in Settings page

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] No new warnings

### CODE REVIEW

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt [hunk 1]
```diff
@@ -502,7 +501,7 @@ class GenerateTestsDialogWindow(val model: GenerateTestsModel) : DialogWrapper(m
 
         model.mockFramework = MOCKITO
         model.staticsMocking = if (staticsMocking.isSelected) MockitoStaticMocking else NoStaticMocking
-        model.codegenLanguage = codegenLanguages.item
+        model.codegenLanguage = model.project.service<Settings>().codegenLanguage//codegenLanguages.item
```
Comment (Damtev) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt:504]: Could we remove the commented code?

**Review by Damtev — CHANGES_REQUESTED** [review]

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt (hunk 1 above)
Comment (Vassiliy-Kudryashov) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt]: This comment may speed-up possible revert to local language choose, but OK.

**Review by Damtev — APPROVED** [review]
