### PR TITLE
Android Studio fixes (#634, #635)

### LINKED ISSUE #634: Android studio: test generation issues
**Description**

Test are not generated in android studio.

**To Reproduce**

1. Open any project in Android Studio
2. Use plugin to generate tests
3. Generation stops midway without exception.

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

No tests are generated.

**Visual proofs (screenshots, logs, images)**

Not applicable.

**Environment**

JDK 11.

**Additional context**

Soot initialization related problem.

### PR DESCRIPTION
**Pull request by nikitavlaev**
# Description

Multiple test modules supported.
Removed unused jdkVersion from model, added for convenience to JdkPathService.
Removed unnecessary classpath modification parts for Android.

Fixes #634, #635

## Type of Change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- Refactoring (typos and non-functional changes) 

# How Has This Been Tested?

## Automated Testing

Not applicable.

## Manual Scenario 

1. Launch Android Studio
2. Install plugin
3. Generate tests for any samples, everything generates without errors.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [x] New tests have been added
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/models/GenerateTestsModel.kt [hunk 1]
```diff
@@ -11,26 +11,40 @@ import org.utbot.framework.plugin.api.CodegenLanguage
...
     var timeout:Long,
     var generateWarningsForStaticMocking: Boolean = false,
     var fuzzingValue: Double = 0.05
 ) {
+    var testModule: Module = potentialTestModules.first()
+    val jdkVersion: JavaSdkVersion?
+        get() = try {
+            testModule.jdkVersion()
+        } catch (e: IllegalStateException) {
+            null
```
Comment (EgorkaKulikov) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/models/GenerateTestsModel.kt:39]: Why did you remove a comment?
// Just ignore it here, notification will be shown in org.utbot.intellij.plugin.ui.utils.ModuleUtilsKt.jdkVersionBy

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/models/GenerateTestsModel.kt [hunk 2]
```diff
@@ -11,26 +11,40 @@ import org.utbot.framework.plugin.api.CodegenLanguage
...
+        }
+
     var testSourceRoot: VirtualFile? = null
+        set(value) {
+            requireNotNull(value)
+            testModule = ModuleUtil.findModuleForFile(value, project) ?: error("Could not find module for $value")
```
Comment (EgorkaKulikov) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/models/GenerateTestsModel.kt:45]: Could we avoid setting one field in a setter for another and setting it with "first()" stub in line 34 before?
Firstly I noticed line 34 and thought "what's the fuck"

**Comment by alisevych** [comment]
### How this has been tested

I've published the plugin as an archive, installed it on IDEA 2022.1.4 and checked how it works on different projects.
Checked Gradle + JDK 8, Maven + JDK 11, Maven + JDK 13 (checked error from UTBot and changed to JDK 11), IntelliJ + JDK 8.
Checked test generation into corrected packages structure.
Checked test generation to a new test source root (Maven, IntelliJ). Blocked for Gradle if test root/roots is/are configured.
Checked test generation when there are several test roots in a project.

_**The following issue found:**_

**Steps to reproduce:**

1. Create Gradle/Maven/IntelliJ project with JDK 8 / 11
2. Add some classes to the source root
3. Remove all Test source root (or unmark folders as Test source roots)
4. Open UTBot dialog to Create tests

**Expected result:**

/src/test/utbot-tests is suggested to create as Test sources root

**Actual result:**

There is test "set test root" in the Test sources root, user needs to manually create the folder and mark it.
In Gradle project - button to manually select/create folders is disabled - so this issue can't be resolved from UTBot dialog.

**Review by EgorkaKulikov — APPROVED** [review]
