### PR TITLE
Make UtEnumConstModel and UtClassRefModel reference models #414

### LINKED ISSUE #230: ClassCastException when processing UtEnumConstantModel
**Description**

Processing of `Enum` types may result in `ClassCastException`, as `UtEnumConstantModel` is incorrectly cast to `UtReferenceModel` in several situations, in particular:

  * `ArrayObjectWrappers.kt`: `AssociativeArrayWrapper.value()` (the location related to the reproducible example below).
  * `CollectionWrappers.kt`: `constructKeysAndValues()` (a similar type cast).

**To Reproduce**

Generate the test suite for the `MapExamples` class.

`Color.java`:
```
public enum Color {
    UNDEFINED,
    RED,
    YELLOW,
    GREEN
}
```

`MapExamples.java`:
```
public class MapExamples {
    public Color[] transduce(@NotNull Color[] inputs, @NotNull HashMap<Color, Color> fst) {
        if (inputs.length > 0) {
            Color[] result = new Color[inputs.length];
            for (int i = 0; i < inputs.length; i++) {
                result[i] = fst.getOrDefault(inputs[i], Color.UNDEFINED);
            }
            return result;
        } else {
            return new Color[0];
        }
    }

    public Color[] trafficLightTransduce(@NotNull Color[] inputs) {
        HashMap<Color, Color> trafficLight = new HashMap<>();
        trafficLight.put(Color.RED, Color.GREEN);
        trafficLight.put(Color.GREEN, Color.YELLOW);
        trafficLight.put(Color.YELLOW, Color.RED);

        return transduce(inputs, trafficLight);
    }
}
```

**Expected behavior**

Test suite is generated, no `ClassCastException` errors are reported.

**Actual behavior**

No tests are generated, the plugin fails with the following exception:

```
java.lang.ClassCastException: class org.utbot.framework.plugin.api.UtEnumConstantModel cannot be cast to class org.utbot.framework.plugin.api.UtReferenceModel (org.utbot.framework.plugin.api.UtEnumConstantModel and org.utbot.framework.plugin.api.UtReferenceModel are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @56d6d8d8)
	at org.utbot.engine.AssociativeArrayWrapper.value(ArrayObjectWrappers.kt:382)
	at org.utbot.engine.Resolver.resolveObject(Resolver.kt:454)
	at org.utbot.engine.Resolver.resolveReferenceValue(Resolver.kt:424)
	at org.utbot.engine.Resolver.resolveModel(Resolver.kt:395)
	at org.utbot.engine.Resolver.collectFieldModels(Resolver.kt:581)
	at org.utbot.engine.MapWrapper.resolveValueModels(CollectionWrappers.kt:309)
	at org.utbot.engine.BaseCollectionWrapper.value(CollectionWrappers.kt:108)
	at org.utbot.engine.BaseCollectionWrapper.value(CollectionWrappers.kt:99)
	at org.utbot.engine.Resolver.resolveObject(Resolver.kt:454)
	at org.utbot.engine.Resolver.resolveReferenceValue(Resolver.kt:424)
	at org.utbot.engine.Resolver.resolveModel(Resolver.kt:395)
	at org.utbot.engine.Resolver.internalResolveModel(Resolver.kt:233)
	at org.utbot.engine.Resolver.resolveModels$utbot_framework(Resolver.kt:204)
	at org.utbot.engine.UtBotSymbolicEngine$traverseImpl$1.invokeSuspend(UtBotSymbolicEngine.kt:466)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.utbot.common.ConcurrencyKt.runBlockingWithCancellationPredicate(Concurrency.kt:38)
	at org.utbot.framework.plugin.api.UtBotTestCaseGenerator$generateForSeveralMethods$4.invoke(UtBotTestCaseGenerator.kt:263)
	at org.utbot.framework.plugin.api.UtBotTestCaseGenerator$generateForSeveralMethods$4.invoke(UtBotTestCaseGenerator.kt:56)
	at org.utbot.common.ConcurrencyKt.runIgnoringCancellationException(Concurrency.kt:47)
	at org.utbot.framework.plugin.api.UtBotTestCaseGenerator.generateForSeveralMethods(UtBotTestCaseGenerator.kt:262)
	at org.utbot.framework.plugin.api.UtBotTestCaseGenerator.generateForSeveralMethods$default(UtBotTestCaseGenerator.kt:249)
	at org.utbot.intellij.plugin.generator.CodeGenerator.generateForSeveralMethods(CodeGenerator.kt:53)
	at org.utbot.intellij.plugin.ui.UtTestsDialogProcessor$createTests$2$1.run(UtTestsDialogProcessor.kt:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

It is possible that some tests are generated, but a non-empty error suite is generated as well (I encountered this case once but it seems hard to reproduce). See **Additional context** below for details.

**Environment**

Mock strategy: *Other packages: Mockito*
Mock static: *No static mocking*
Test framework: *JUnit5*

**Additional context**

I somehow managed to generate a non-empty test suite with several reported `ClassCastException` errors. It seems hard to reproduce (usually the generator just fails, so I am not sure that it is not a version mismatch from my side), but it might be useful to have this log.

```
public class MapExamplesTest {
    ///region Test suites for executable collections.MapExamples.transduce

    ///region SUCCESSFUL EXECUTIONS for method transduce(collections.Color[], java.util.HashMap)

    /**
     * <pre>
     * Test does not iterate {@code for(int i = 0; i < inputs.length; i++) }, executes conditions:
     *     {@code (inputs.length > 0): False }
     * returns from: {@code return new Color[0]; }
     * </pre>
     */
    @Test
    @DisplayName("transduce: inputs.length > 0 : False -> return new Color[0]")
    public void testTransduce_InputsLengthLessOrEqualZero() {
        MapExamples mapExamples = new MapExamples();
        Color[] colorArray = {};
        HashMap hashMap = new HashMap();

        Color[] actual = mapExamples.transduce(colorArray, hashMap);

        Color[] expected = {};

        int expectedSize = expected.length;
        assertEquals(expectedSize, actual.length);
        assertTrue(deepEquals(expected, actual));
    }

    /**
     * <pre>
     * Test executes conditions:
     *     {@code (inputs.length > 0): True }
     * iterates the loop {@code for(int i = 0; i < inputs.length; i++) } once.
     * Test then returns from: {@code return result; }
     * </pre>
     */
    @Test
    @DisplayName("transduce: inputs.length > 0 : True -> return result")
    public void testTransduce_InputsLengthGreaterThanZero() throws ClassNotFoundException, Exception {
        Color prevUNDEFINED = Color.UNDEFINED;
        try {
            Color undefined = Color.UNDEFINED;
            Class colorClazz = Class.forName("collections.Color");
            setStaticField(colorClazz, "UNDEFINED", undefined);
            MapExamples mapExamples = new MapExamples();
            Color[] colorArray = {null};
            HashMap hashMap = new HashMap();

            Color[] actual = mapExamples.transduce(colorArray, hashMap);

            Color[] expected = new Color[1];
            Color color = Color.UNDEFINED;
            expected[0] = color;

            int expectedSize = expected.length;
            assertEquals(expectedSize, actual.length);
            assertTrue(deepEquals(expected, actual));

            Color finalColorArray0 = colorArray[0];

            assertNull(finalColorArray0);
        } finally {
            setStaticField(Color.class, "UNDEFINED", prevUNDEFINED);
        }
    }
    ///endregion

    ///region Errors report for transduce

    public void testTransduce_errors() {
        // Couldn't generate some tests. List of errors:
        // 
        // 18 occurrences of:
        /* class org.utbot.framework.plugin.api.UtEnumConstantModel cannot be cast to class org.utbot.framework.plugin.api.UtReferenceModel (org.utbot.framework.plugin.api.UtEnumConstantModel and
        org.utbot.framework.plugin.api.UtReferenceModel are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @33114743) */

    }
    ///endregion

    ///endregion

    ///region Test suites for executable collections.MapExamples.trafficLightTransduce

    ///region SUCCESSFUL EXECUTIONS for method trafficLightTransduce(collections.Color[])

    /**
     * <pre>
     * Test calls MapExamples::transduce,
     *     there it does not iterate {@code for(int i = 0; i < inputs.length; i++) }, executes conditions:
     *         {@code (inputs.length > 0): False }
     *     returns from: {@code return new Color[0]; }
     *
     * Test afterwards returns from: {@code return transduce(inputs, trafficLight); }
     * </pre>
     */
    @Test
    @DisplayName("trafficLightTransduce: inputs.length > 0 : False -> return new Color[0]")
    public void testTrafficLightTransduce_InputsLengthLessOrEqualZero() throws ClassNotFoundException, Exception {
        Color prevRED = Color.RED;
        Color prevGREEN = Color.GREEN;
        Color prevYELLOW = Color.YELLOW;
        try {
            Color red = Color.RED;
            Class colorClazz = Class.forName("collections.Color");
            setStaticField(colorClazz, "RED", red);
            Color green = Color.GREEN;
            setStaticField(colorClazz, "GREEN", green);
            Color yellow = Color.YELLOW;
            setStaticField(colorClazz, "YELLOW", yellow);
            MapExamples mapExamples = new MapExamples();
            Color[] colorArray = {};

            Color[] actual = mapExamples.trafficLightTransducer(colorArray);

            Color[] expected = {};

            int expectedSize = expected.length;
            assertEquals(expectedSize, actual.length);
            assertTrue(deepEquals(expected, actual));
        } finally {
            setStaticField(Color.class, "RED", prevRED);
            setStaticField(Color.class, "GREEN", prevGREEN);
            setStaticField(Color.class, "YELLOW", prevYELLOW);
        }
    }

    /**
     * <pre>
     * Test calls MapExamples::transduce,
     *     there it executes conditions:
     *         {@code (inputs.length > 0): True }
     *     iterates the loop {@code for(int i = 0; i < inputs.length; i++) } once.
     *     Test then returns from: {@code return result; }
     *
     * Test next returns from: {@code return transduce(inputs, trafficLight); }
     * </pre>
     */
    @Test
    @DisplayName("trafficLightTransduce: inputs.length > 0 : True -> return result")
    public void testTrafficLightTransduce_InputsLengthGreaterThanZero() throws ClassNotFoundException, Exception {
        Color prevRED = Color.RED;
        Color prevGREEN = Color.GREEN;
        Color prevYELLOW = Color.YELLOW;
        Color prevUNDEFINED = Color.UNDEFINED;
        try {
            Color red = Color.RED;
            Class colorClazz = Class.forName("collections.Color");
            setStaticField(colorClazz, "RED", red);
            Color green = Color.GREEN;
            setStaticField(colorClazz, "GREEN", green);
            Color yellow = Color.YELLOW;
            setStaticField(colorClazz, "YELLOW", yellow);
            Color undefined = Color.UNDEFINED;
            setStaticField(colorClazz, "UNDEFINED", undefined);
            MapExamples mapExamples = new MapExamples();
            Color[] colorArray = {null};

            Color[] actual = mapExamples.trafficLightTransducer(colorArray);

            Color[] expected = new Color[1];
            Color color = Color.UNDEFINED;
            expected[0] = color;

            int expectedSize = expected.length;
            assertEquals(expectedSize, actual.length);
            assertTrue(deepEquals(expected, actual));

            Color finalColorArray0 = colorArray[0];

            assertNull(finalColorArray0);
        } finally {
            setStaticField(Color.class, "RED", prevRED);
            setStaticField(Color.class, "GREEN", prevGREEN);
            setStaticField(Color.class, "YELLOW", prevYELLOW);
            setStaticField(Color.class, "UNDEFINED", prevUNDEFINED);
        }
    }
    ///endregion

    ///endregion
}
```

### LINKED ISSUE #300: Absent class name in static constant usage
**Description**

If we generate tests using the contest estimator for `com.google.common.base.CaseFormat`, we will see that the resulting file does not compile because of absent class name in static constant usage: ` expectedFinalCaseFormat = .UPPER_CAMEL`.

**To Reproduce**

1. Run the contest estimator for `com.google.common.base.CaseFormat` with 300s time limit
2. Open generated file

**Expected behaviour**

Compilable file.

**Actual behaviour**

Generated file does not compile.

**Visual proofs (screenshots, logs, images)**
image

**Environment**

The default environment for the contest estimator.

**Additional context**

There is no additional context.

### LINKED ISSUE #414: Make UtEnumConstantModel and UtClassRefModel subclasses of UtReferenceModel
**Description**

Although `Enum` is a reference type, `UtEnumConstantModel` is not currently a subtype of `UtReferenceModel` and does not have any `id` that would allow the reference comparison of `Enum` values. As a result, we can't use `Enum` values as elements of generic collections (`Map<K, V>`, `List<E>` etc).

The intended solution:
  * `UtEnumConstantModel` and `UtClassRefModel` should be subtypes of `UtReferenceModel`.
  * The address assigned to a `UtEnumConstantModel` should be equal to one and only one address assigned to models of the static fields of the corresponding `Enum` class, and reference equality must hold.
  * The addresses should be assigned to `UtClassRefModel` with respect to class equality condition: all models of the same class should have the same address, models of different classes should have different addresses,

Related issue: #230 

**Expected behavior**

`UtEnumConstantModel` is a subtype of `UtReferenceModel`, and enum values can be used as elements of any generic collection.

**Environment**

The intended behavior does not depend on any specific environment.

### PR DESCRIPTION
**Pull request by dtim**
# Description

Historically `UtEnumConstModel` and `UtClassRefModel` have been processed not as other reference models, but in a special way, more like to primitive types. This approach leads to several problems, especially to class cast errors when processing generic collections with enums or class references as elements.

This commit makes `UtEnumConstModel` and `UtClassRefModel` subtypes of `UtReferenceModel`.

  * Concrete executor is modified to respect the identity of static fields to avoid rewriting enum values and `Class<?>` instances.

  * Special processing for enums is implemented. When a new enum value is created, or an `Object` is being cast to the enum type, static values for the enum class are initialized, and the set of hard constraint is added to require that the new instance has the same address and ordinal as any one of enum constants to implement reference equality for enums.

  * Corresponding changes in fuzzer model providers have been implemented.

Limitations (probably have been there for a long time, addressed separately):
  * anonymous nested classes associated with enum values are not fully supported yet: #617 (maybe a codegen limitation);
  * enum constants are explicitly assigned to corresponding static fields in generated tests: #618 (it seems to be a particular case of our general approach to static field initialization);
  * instances of enum classes are (unsuccessfully) generated via reflection by the concrete executor: #619.

Fixes #414 (meta-issue)
Fixes #230
Fixes #300

## Type of Change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Automated Testing

All existing unit tests should pass.

New unit tests for enums have been added: `org.utbot.examples.enums.ComplexEnumExamplesTest`

Note: the test `org.utbot.examples.enums.ComplexEnumExamplesTest#testFindState` is currently disabled because of limited anonymous classes support.

## Manual Scenario 

To check that #230 is fixed: generate the test suite for the code example in issue #230 description. Test should be generated, no exceptions should be thrown.

To check that #300 is fixed: run the contest estimator with settings from issue #300 description. Generated file should compile, class name should be present in qualified enum constant names.

# Checklist:

_This is the author self-check list_

- [X] The change followed the style guidelines of the UTBot project
- [X] Self-review of the code is passed
- [X] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [X] No new warnings
- [X] New tests have been added
- [X] All tests pass locally with my changes

### CODE REVIEW

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt [hunk 1]
```diff
@@ -266,6 +266,15 @@ fun UtModel.hasDefaultValue() =
  */
 fun UtModel.isMockModel() = this is UtCompositeModel && isMock
 
+/**
+ * Get model id or null if id is null or the model has no id.
+ */
+fun UtModel.idOrNull(): Int? = when (this) {
+    is UtNullModel -> 0
```
Comment (Damtev) [inline utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt:273]: Could you link this constant with `org.utbot.engine.ResolverKt#NULL_ADDR` somehow, please?

File: utbot-framework/src/main/kotlin/org/utbot/engine/CollectionWrappers.kt [hunk 2]
```diff
@@ -373,7 +374,7 @@ private fun constructKeysAndValues(keysModel: UtModel, valuesModel: UtModel, siz
         keysModel is UtArrayModel && valuesModel is UtArrayModel -> {
             List(size) {
                 keysModel.stores[it].let { model ->
-                    val addr = if (model is UtNullModel) 0 else (model as UtReferenceModel).id
+                    val addr = model?.idOrNull() ?: throw IllegalStateException("Unsupported model: $model")
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/engine/CollectionWrappers.kt:377]: Perhaps it is better to introduce a new extension for `UtModel` that performs such action.

File: utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt [hunk 3]
```diff
@@ -350,6 +353,9 @@ data class Memory( // TODO: split purely symbolic memory and information about s
     fun findStaticInstanceOrNull(id: ClassId): ObjectValue? = staticInstanceStorage[id]
 
     fun findTypeForArrayOrNull(addr: UtAddrExpression): ArrayType? = addrToArrayType[addr]
+
+    fun getSymbolicEnumValues(classId: ClassId): Collection<ObjectValue> =
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt:357]: Why not `List` return type?

File: utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt [hunk 4]
```diff
@@ -986,7 +993,11 @@ data class MemoryUpdate(
             classIdToClearStatics = other.classIdToClearStatics,
             instanceFieldReads = instanceFieldReads.addAll(other.instanceFieldReads),
             speculativelyNotNullAddresses = speculativelyNotNullAddresses.addAll(other.speculativelyNotNullAddresses),
+            symbolicEnumValues = symbolicEnumValues.addAll(other.symbolicEnumValues),
         )
+
+    fun getSymbolicEnumValues(classId: ClassId): Collection<ObjectValue> =
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt:999]: Same about `List`

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 5]
```diff
@@ -564,14 +561,25 @@ class Traverser(
...
 
+    @Suppress("UnnecessaryVariable")
+    private fun makeConcreteUpdatesForEnumsWithStmt(
+        fieldId: FieldId,
+        declaringClass: SootClass,
+        stmt: Stmt
+    ): SymbolicStateUpdate {
+        val (enumUpdates, curFieldSymbolicValueForLocalVariable) =
+            makeConcreteUpdatesForEnum(declaringClass.type, fieldId)
+        val allUpdates =  enumUpdates + createConcreteLocalValueUpdate(stmt, curFieldSymbolicValueForLocalVariable)
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:582]: Redundant  ` `

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 6]
```diff
@@ -564,14 +561,25 @@ class Traverser(
...
-                nonStaticFieldsUpdates +
-                initializedStaticFieldsMemoryUpdate +
-                createConcreteLocalValueUpdate(stmt, curFieldSymbolicValueForLocalVariable)
+        return Pair(
+            staticFieldUpdates + nonStaticFieldsUpdates + initializedStaticFieldsMemoryUpdate,
+            curFieldSymbolicValueForLocalVariable
+        )
+    }
 
+    @Suppress("UnnecessaryVariable")
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:574]: I guess this suppression is no longer applicable.

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 7]
```diff
@@ -1373,6 +1381,39 @@ class Traverser(
...
+        val enumValueConstraints = mkOr(
+            listOf(addrEq(addr, nullObjectAddr)) + predefinedEnumValues.map {
+                mkAnd(
+                    addrEq(addr, it.addr),
+                    mkEq(ordinal, findEnumOrdinal(it.type, it.addr))
+                )
+            }
+        )
+
+        queuedSymbolicStateUpdates += mkOr(enumValueConstraints).asHardConstraint()
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:1414]: Why do we need one more `mkOr`?

File: utbot-framework/src/main/kotlin/org/utbot/framework/concrete/UtExecutionInstrumentation.kt [hunk 8]
```diff
@@ -178,7 +178,15 @@ object UtExecutionInstrumentation : Instrumentation<UtConcreteExecutionResult> {
...
                         .associateWith { fieldId ->
-                            fieldId.field.run { construct(withAccessibility { get(null) }, fieldId.type) }
+                            fieldId.field.run {
+                                val computedValue = withAccessibility { get(null) }
+                                val knownModel = stateBefore.statics[fieldId]
+                                val knownValue = staticFields[fieldId]
+                                if (knownModel != null && knownValue != null && knownValue == computedValue)
+                                    knownModel
+                                else
+                                    construct(computedValue, fieldId.type)
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/framework/concrete/UtExecutionInstrumentation.kt:188]: Could you please use curly braces here?

File: utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt [hunk 9]
```diff
@@ -0,0 +1,106 @@
...
+        )
+    }
+
+    @Test
+    fun testCountEqualColors() {
+        check(
+            ComplexEnumExamples::countEqualColors,
+            ignoreExecutionsNumber,
+            { a, b, c, r -> a == b && a == c && r == 3 },
+            { a, b, c, r -> ((a == b && b != c) || (a != b && a == c)) && r == 2 },
```
Comment (Damtev) [inline utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt:61]: `setOf(a, b, c).size == 2`?

File: utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt [hunk 10]
```diff
@@ -0,0 +1,106 @@
...
+        )
+    }
+
+    @Test
+    fun testCountNullColors() {
+        check(
+            ComplexEnumExamples::countNullColors,
+            eq(3),
+            { a, b, r -> a == null && b == null && r == 2 },
+            { a, b, r -> ((a != null && b == null) || (a == null && b != null)) && r == 1 },
```
Comment (Damtev) [inline utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt:72]: `(a == null) != (b == null)`?

File: utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt [hunk 11]
```diff
@@ -0,0 +1,106 @@
...
+            { a, b, r -> a != null && b != null && r == 0 },
+        )
+    }
+
+    @Test
+    @Disabled("TODO: Nested anonymous classes in enums do not work well yet")
```
Comment (Damtev) [inline utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt:78]: Do we have an issue with it?

File: utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt [hunk 12]
```diff
@@ -0,0 +1,106 @@
...
+    }
+
+    @Test
+    fun testCountValuesInArray() {
+        check(
+            ComplexEnumExamples::countValuesInArray,
+            ignoreExecutionsNumber,
+            { cs, r -> cs.isEmpty() && r != null && r.isEmpty() },
+            { cs, r -> cs.filter { it != null }.isEmpty() && r != null && r.isEmpty() },
+            { cs, r -> cs.filter { it != null }.isNotEmpty() && r != null && Color.values().all { clr -> cs.count { it == clr } == (r[clr] ?: 0) } }
```
Comment (Damtev) [inline utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt:94]: It is very difficult to read, could you break it into a few lines, please?

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt [hunk 13]
```diff
@@ -307,20 +316,64 @@ object UtVoidModel : UtModel(voidClassId)
...
+        return true
+    }
+
+
+    override fun hashCode(): Int {
+        var result = id ?: 0
+        result = 31 * result + classId.hashCode()
+        result = 31 * result + value.hashCode()
+        return result
+    }
```
Comment (Damtev) [inline utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt:344]: Why do weed these overrides? It is a data class already

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt [hunk 14]
```diff
@@ -307,20 +316,64 @@ object UtVoidModel : UtModel(voidClassId)
...
+
+        return true
+    }
+
+    override fun hashCode(): Int {
+        var result = id ?: 0
+        result = 31 * result + classId.hashCode()
+        result = 31 * result + value.hashCode()
+        return result
+    }
```
Comment (Damtev) [inline utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt:376]: Same about overrides

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt [hunk 15]
```diff
@@ -307,20 +316,64 @@ object UtVoidModel : UtModel(voidClassId)
  * Model for enum constant
  */
 data class UtEnumConstantModel(
+    override val id: Int?,
     override val classId: ClassId,
     val value: Enum<*>
-) : UtModel(classId) {
-    override fun toString(): String = "$value"
+) : UtReferenceModel(id, classId) {
+    override fun toString(): String = "$value@$id"
```
Comment (Damtev) [inline utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt:323]: Are you sure about this `@` sign?

File: utbot-sample/src/main/java/org/utbot/examples/enums/ComplexEnumExamples.java [hunk 16]
```diff
@@ -0,0 +1,116 @@
+package org.utbot.examples.enums;
+
+import org.jetbrains.annotations.NotNull;
+
+import java.util.HashMap;
+import java.util.LinkedList;
+import java.util.List;
+import java.util.Map;
+
+public class ComplexEnumExamples {
```
Comment (Damtev) [inline utbot-sample/src/main/java/org/utbot/examples/enums/ComplexEnumExamples.java:10]: Same about curly braces for conditional expressions

**Review by Damtev — CHANGES_REQUESTED** [review]
Logic LGTM, some issues about codestyle

File: utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt (hunk 3 above)
Comment (dtim) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt]: Sure, thank you.

File: utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt (hunk 4 above)
Comment (dtim) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Memory.kt]: Fixed this as well.

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt (hunk 5 above)
Comment (dtim) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt]: Fixed.

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt (hunk 6 above)
Comment (dtim) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:574]: It is required as otherwise IDEA would suggest to get rid of `allUpdates`. It is easy to use a direct `return` here and in the next function (`makeConcreteUpdatesForNonEnumStaticField`), but I decided to keep the previous approach (it seems a bit more readable for me, although the difference is not so big). I can replace `allUpdates` with `return enumUpdates + ...` here if you think it would be better.

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt (hunk 7 above)
Comment (dtim) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt]: We don't, thank you. I forgot to remove it when I last changed the code.

File: utbot-framework/src/main/kotlin/org/utbot/framework/concrete/UtExecutionInstrumentation.kt (hunk 8 above)
Comment (dtim) [reply utbot-framework/src/main/kotlin/org/utbot/framework/concrete/UtExecutionInstrumentation.kt]: Done.

File: utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt (hunk 9 above)
Comment (dtim) [reply utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt]: Yes, it seems better, thank you.

File: utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt (hunk 11 above)
Comment (dtim) [reply utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt]: Yes, #617. I added a link to the issue to the comment.

File: utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt (hunk 12 above)
Comment (dtim) [reply utbot-framework/src/test/kotlin/org/utbot/examples/enums/ComplexEnumExamplesTest.kt]: I noticed an incorrect usage of `@NotNull` annotation on arrays in the Java code (my understanding of the `@NotNull` semantics was incomplete), so I rewrote the test a bit to make it correct again. Hope it's more clear now.

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt (hunk 13 above)
Comment (dtim) [reply utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt]: Yes, it was an artifact left from an early version. Thank you, I removed it.

File: utbot-framework/src/main/kotlin/org/utbot/engine/CollectionWrappers.kt (hunk 2 above)
Comment (Damtev) [reply utbot-framework/src/main/kotlin/org/utbot/engine/CollectionWrappers.kt:377]: I just meant an extension function like this:

```kotlin
fun UtModel.id(): Int = idOrNull() ?: throw IllegalStateException("Unsupported model: $this")
```

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt (hunk 15 above)
Comment (dtim) [reply utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt:327]: I replaced ":" with "@" in both locations, as it seems more readable. I'd like to keep these `id` values for debugging, at least until related issues are fixed.

File: utbot-sample/src/main/java/org/utbot/examples/enums/ComplexEnumExamples.java (hunk 16 above)
Comment (dtim) [reply utbot-sample/src/main/java/org/utbot/examples/enums/ComplexEnumExamples.java:10]: Done.

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt (hunk 6 above)
Comment (Damtev) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:574]: Yeah, I see, it's my misunderstanding - I read not carefully and mixed up `UnnecessaryVariable` with `UNUSED_PARAMETER`. Keep it as it is, please.

File: utbot-framework/src/main/kotlin/org/utbot/engine/CollectionWrappers.kt (hunk 2 above)
Comment (dtim) [reply utbot-framework/src/main/kotlin/org/utbot/engine/CollectionWrappers.kt]: A solution that does not break smart casts: an extension function with a contract (thanks to @ArsenHD).

**Review by Damtev — APPROVED** [review]

File: utbot-framework/src/main/kotlin/org/utbot/engine/symbolic/SymbolicStateUpdate.kt [hunk 17]
```diff
@@ -5,6 +5,11 @@ import org.utbot.engine.MemoryUpdate
 import org.utbot.engine.pc.UtBoolExpression
 import kotlinx.collections.immutable.PersistentSet
 import kotlinx.collections.immutable.toPersistentSet
+import org.utbot.engine.StaticFieldMemoryUpdateInfo
+import org.utbot.engine.UtNamedStore
+import org.utbot.framework.plugin.api.ClassId
+import org.utbot.framework.plugin.api.FieldId
+import org.utbot.framework.plugin.api.classId
```
Comment (sergeypospelov) [inline utbot-framework/src/main/kotlin/org/utbot/engine/symbolic/SymbolicStateUpdate.kt:12]: Looks like these imports are redundant.

**Review by sergeypospelov — APPROVED** [review]
The concrete part looks good to me.

**Comment by dtim** [comment]
Updated `UtModelVisitor` and `FieldStateVisitor` to reflect model hierarchy change.

**Review by Markoutte — APPROVED** [review]

**Review by Markoutte — APPROVED** [review]
