### PR TITLE
Fix engine to properly handle hidden fields #647

### LINKED ISSUE #647: Engine treats hidden field and the field it is hidden by as the same field
**Description**

If we generate tests for the class with hidden fields, generated model is incorrect, because for engine all fields with the same name in one class are the same.

**To Reproduce**

Launch `HiddenFieldExampleTest` or `HiddenFieldAccessModifiersTest`.

**Expected behavior**

Tests passed.

**Actual behavior**

Tests doesn't work because generated model is incorrect.

**Additional context**

This is a sub-issue for #563, look there for more information and examples.

### PR DESCRIPTION
**Pull request by volivan239**
# Description

Now if class has hidden fields, they can be recognized by engine and correct models are built.

Fixes #647

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Automated Testing

Switched `org.utbot.examples.objects.HiddenFieldExampleTest#testCheckSuccField` to enabled, added `org.utbot.examples.objects.HiddenFieldAccessModifiersTest`

## Manual Scenario 

No manual scenario for testing this.

# Checklist (remove irrelevant options):

_This is the author self-check list_
- [ ] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [ ] No new warnings
- [x] New tests have been added
- [ ] All tests pass locally with my changes

### CODE REVIEW

**Comment by volivan239** [comment]
This PR is derived from #592. See this [comment](https://github.com/UnitTestBot/UTBotJava/pull/592#issuecomment-1201120069) for more details.

**Comment by volivan239** [comment]
Problems discovered in previous PR that were fixed but the fixes were not reviewed:

* Changes in `IdUtil.kt` (naming and logic)
* Naming problem in `Traverser.kt:642`

File: utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldAccessModifiersTest.kt [hunk 1]
```diff
@@ -0,0 +1,21 @@
+package org.utbot.examples.objects
+
+import org.utbot.examples.UtValueTestCaseChecker
+import org.utbot.examples.eq
+import org.junit.jupiter.api.Test
+
+internal class HiddenFieldAccessModifiersTest : UtValueTestCaseChecker(testClass = HiddenFieldAccessModifiersExample::class) {
+    @Test
+    fun testCheckSuperFieldEqualsOne() {
+        // TODO: currently, codegen can't handle tests with field hiding
```
Comment (Damtev) [inline utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldAccessModifiersTest.kt:10]: Create an issue and mention it here, please

File: utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldExampleTest.kt [hunk 2]
```diff
@@ -22,18 +20,18 @@ internal class HiddenFieldExampleTest : UtValueTestCaseChecker(testClass = Hidde
...
-            HiddenFieldExample::checkSuccField,
-            eq(5),
-            { o, _ -> o == null },
-            { o, r -> o.a == 1 && r == 1 },
-            { o, r -> o.a != 1 && o.b == 2.0 && r == 2 },
-            { o, r -> o.a != 1 && o.b != 2.0 && (o as HiddenFieldSuperClass).b == 3 && r == 3 },
-            { o, r -> o.a != 1 && o.b != 2.0 && (o as HiddenFieldSuperClass).b != 3 && r == 4 },
-            coverage = DoNotCalculate
-        )
+        // TODO: currently, codegen can't handle tests with field hiding
```
Comment (Damtev) [inline utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldExampleTest.kt:24]: Same about issue

**Review by Damtev — CHANGES_REQUESTED** [review]

File: utbot-framework/src/main/kotlin/org/utbot/engine/Strings.kt [hunk 3]
```diff
@@ -313,7 +313,7 @@ sealed class UtAbstractStringBuilderWrapper(className: String) : BaseOverriddenW
 
         val arrayValuesChunkId = typeRegistry.arrayChunkId(charArrayType)
 
-        val valuesFieldChunkId = hierarchy.chunkIdForField(utStringClass.type, overriddenClass.valueField)
+        val valuesFieldChunkId = hierarchy.chunkIdForField(utStringClass.type, utStringClass.valueField)
```
Comment (dtim) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Strings.kt:316]: Replacement of `overriddenClass.valueField` with `utStringClass.valueField` seems incorrect, as we are dealing with `UtStringBuilder`/`UtStringBuffer` and not `UtString`. At the same time, the first argument `utStringClass.type` seems suspicious.

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 4]
```diff
@@ -634,12 +634,16 @@ class Traverser(
...
     // TODO JIRA:1593
-    private fun extractConcreteValue(field: SootField, declaringClass: SootClass): Any? =
+    private fun extractConcreteValue(field: SootField): Any? =
         when (field.signature) {
             SECURITY_FIELD_SIGNATURE -> SecurityManager()
             FIELD_FILTER_MAP_FIELD_SIGNATURE -> mapOf(Reflection::class to arrayOf("fieldFilterMap", "methodFilterMap"))
             METHOD_FILTER_MAP_FIELD_SIGNATURE -> emptyMap<Class<*>, Array<String>>()
-            else -> declaringClass.id.jClass.findField(field.name).let { it.withAccessibility { it.get(null) } }
+            else -> {
+                val id = field.fieldId
```
Comment (dtim) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:643]: This code seems not very clear, too many `id`s. Maybe rename `id` to a more descriptive name?

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt [hunk 5]
```diff
@@ -303,11 +310,12 @@ fun ClassId.defaultValueModel(): UtModel = when (this) {
...
 
 // FieldId utils
+val FieldId.safeField: Field?
+    get() = declaringClass.jClass.declaredFields.firstOrNull { it.name == name }
 
 // TODO: maybe cache it somehow in the future
 val FieldId.field: Field
-    get() = declaringClass.jClass.declaredFields.firstOrNull { it.name == name }
-        ?: error("Field $name is not found in class ${declaringClass.jClass.name}")
+    get() = safeField ?: error("Field $name is not found in class ${declaringClass.jClass.name}")
```
Comment (dtim) [inline utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt:318]: If we have a `ClassId.jClass`, maybe it would be consistent to rename `FieldId.field` to `FieldId.jField`?

**Review by dtim — CHANGES_REQUESTED** [review]
Generally OK, but a fix in `UtAbstractStringBuilderWrapper.value()` needs correction.

As you fix only the engine part, I think it could be useful to create two separate issues, one for the engine, and another for the codegen ("children" of #563 and linked to it). That way you could reference (and close) the relevant issue and keep another issue open, and then close both the remaining issue and the parent issue with a second PR.

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt (hunk 5 above)
[the remark this answers is not in the document]
Comment (volivan239) [reply utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt:318]: done

File: utbot-framework/src/main/kotlin/org/utbot/engine/Hierarchy.kt [hunk 6]
```diff
@@ -28,10 +28,12 @@ class Hierarchy(private val typeRegistry: TypeRegistry) {
         type as? RefType ?: error("$type is not a refType")
 
         val realType = typeRegistry.findRealType(type) as RefType
+        val realFieldDeclaringType = typeRegistry.findRealType(field.declaringClass.type) as RefType
```
[the remark this answers is not in the document]
Comment (volivan239) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Hierarchy.kt:31]: The linked comment was actually resolved, so fixed now

File: utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldAccessModifiersTest.kt (hunk 1 above)
Comment (volivan239) [reply utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldAccessModifiersTest.kt:10]: done

File: utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldExampleTest.kt (hunk 2 above)
Comment (volivan239) [reply utbot-framework/src/test/kotlin/org/utbot/examples/objects/HiddenFieldExampleTest.kt:24]: done

File: utbot-core/src/main/kotlin/org/utbot/common/KClassUtil.kt [hunk 7]
```diff
@@ -7,22 +7,14 @@ import java.lang.reflect.Method
...
-                it.getDeclaredField(name)
-            } catch (e: NoSuchFieldException) {
-                null
-            }
-        }
-    }
-    .firstOrNull()
+/**
+ * Returns the Field that would be used by compiler when you try to direct access [fieldName] from code, i.e.
+ * when you write `${this.name}.$fieldName`.
```
[the remark this answers is not in the document]
Comment (volivan239) [reply utbot-core/src/main/kotlin/org/utbot/common/KClassUtil.kt:12]: This is a valuable comment, but I found out that this function is not even needed in this PR, so this is to be fixed in #592

File: utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt (hunk 5 above)
Comment (volivan239) [reply utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt:318]: fixed

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 8]
```diff
@@ -634,12 +634,16 @@ class Traverser(
...
+                val jField = id.field
+                jField.let { it.withAccessibility { it.get(null) } }
```
[the remark this answers is not in the document]
Comment (volivan239) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt]: fixed

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt (hunk 4 above)
Comment (volivan239) [reply utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt]: replaced with `fieldId`

**Review by dtim — APPROVED** [review]
LGTM

**Review by Damtev — APPROVED** [review]
