### PR TITLE
Settings cannot be loaded because of NullPointerException #951

### LINKED ISSUE #951: Settings cannot be loaded because of NullPointerException
**Description**

Now visual names and config IDs are shared, so after [Settings UI revision](https://github.com/UnitTestBot/UTBotJava/issues/753) implementation already existing config file (**.idea/utbot-settings.xml**) may contain "unknown" enum names that causes an error during deserialization. 

Corresponding stracktrace looks like this:
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.utbot.intellij.plugin.settings.Settings$State.setMockStrategy, parameter <set-?>
org.utbot.intellij.plugin.settings.Settings$State.setMockStrategy(Settings.kt)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.intellij.serialization.PropertyAccessor.set(PropertyAccessor.java:97)
com.intellij.util.xmlb.XmlSerializerImpl.doSet(XmlSerializerImpl.java:221)
com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:120)
com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:55)
com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:246)
com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:200)
com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:143)
com.intellij.configurationStore.JdomSerializerImpl.deserialize(xmlSerializer.kt:91)
com.intellij.configurationStore.DefaultStateSerializerKt.deserializeState(DefaultStateSerializer.kt:29)
com.intellij.configurationStore.StateStorageBase.deserializeState(StateStorageBase.kt:35)
com.intellij.configurationStore.StateGetterImpl.getState(StorageBaseEx.kt:57)
com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:423)
com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:373)
com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:124)
com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:525)
com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:36)
com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
com.intellij.serviceContainer.ComponentManagerImpl.instantiateService(ComponentManagerImpl.kt:1084)
com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invoke(ComponentManagerImpl.kt:1056)
com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.run(ComponentManagerImpl.kt:58)
java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Solution**
Split IDs into UI-related names and config-related constants.

### PR DESCRIPTION
**Pull request by Vassiliy-Kudryashov**
# Description

Now CodeGenerationSettingItem.toString() goes to serialization and CodeGenerationSettingItem.displayName is being used in UI renderers.

Fixes #951 

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Manual Scenario 

Open recently built plugin with pretty old configured project (somewhen before https://github.com/UnitTestBot/UTBotJava/issues/753 implemenation), startup shouldn't fail (see the issue).
 
# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] No new warnings

### CODE REVIEW

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt [hunk 1]
```diff
@@ -191,6 +192,12 @@ class GenerateTestsDialogWindow(val model: GenerateTestsModel) : DialogWrapper(m
         parametrizedTestSources to null
     )
 
+    private fun <T> createComboBox(values: Array<T>) : ComboBox<T> {
```
Comment (Damtev) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt:195]: I guess we can remove this type parameter and just use `CodeGenerationSettingItem` type instead.

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt [hunk 2]
```diff
@@ -239,22 +246,22 @@ class GenerateTestsDialogWindow(val model: GenerateTestsModel) : DialogWrapper(m
...
-                    codegenLanguages as ComboBox<CodeGenerationSettingItem>,
-                    itemsToHelpTooltip[codegenLanguages]
-                )
-            }.visible = false
+//            row("Code generation language:") {
+//                makePanelWithHelpTooltip(
+//                    codegenLanguages,
+//                    itemsToHelpTooltip[codegenLanguages]
+//                )
+//            }
```
Comment (Damtev) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt:254]: Could we remove this commented code?

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt [hunk 3]
```diff
@@ -959,7 +966,7 @@ class GenerateTestsDialogWindow(val model: GenerateTestsModel) : DialogWrapper(m
                 list: JList<out TestFramework>, value: TestFramework?,
                 index: Int, selected: Boolean, hasFocus: Boolean
             ) {
-                this.append(value.toString(), SimpleTextAttributes.REGULAR_ATTRIBUTES)
+                this.append(value?.displayName?:"<null>", SimpleTextAttributes.REGULAR_ATTRIBUTES)
```
Comment (Damtev) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt:969]: Could you please leave a comment about a situation with null `value`?

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/components/CodeGenerationSettingItemRenderer.kt [hunk 4]
```diff
@@ -0,0 +1,22 @@
+package org.utbot.intellij.plugin.ui.components
+
+import java.awt.Component
+import javax.swing.DefaultListCellRenderer
+import javax.swing.JList
+import org.utbot.framework.plugin.api.CodeGenerationSettingItem
+
+open class CodeGenerationSettingItemRenderer : DefaultListCellRenderer() {
```
Comment (Damtev) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/components/CodeGenerationSettingItemRenderer.kt:8]: Why do we need to make it open? Actually, looking at its usage, I suppose it could just be an object, wouldn't it?

**Review by Damtev — CHANGES_REQUESTED** [review]

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt (hunk 1 above)
Comment (Vassiliy-Kudryashov) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt:195]: It still might be useful if we decide to return back codegen language control

Comment (Vassiliy-Kudryashov) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt:195]: It would break lines like
        model.testFramework = testFrameworks.item
        model.mockStrategy = mockStrategies.item

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/components/CodeGenerationSettingItemRenderer.kt (hunk 4 above)
Comment (Vassiliy-Kudryashov) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/components/CodeGenerationSettingItemRenderer.kt]: Let it be internal class with couple of usages

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt (hunk 2 above)
Comment (Vassiliy-Kudryashov) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt]: OK, let it stay in git log only

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt (hunk 1 above)
Comment (Damtev) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt:195]: Well, at least we can use an upper-bound `T : CodeGenerationSettingItem`

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt (hunk 3 above)
Comment (Damtev) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt:964]: Discussed

**Review by Damtev — CHANGES_REQUESTED** [review]

**Review by Damtev — APPROVED** [review]
