### PR TITLE
Fix rendering for different IDE versions

### LINKED ISSUE #1078: Java docs with plain text are rendered incorrectly
**Description**

Java docs with plain text are rendered incorrectly.

**To Reproduce**

1. Run UTBotJava project in IntelliJ Idea 2022.1.4
2. Set Java doc style to "Plain text"
3. Open utbot-sample/src/main/java/org/utbot/examples/algorithms/ArraysQuickSort.java
4. Use plugin to generate tests - [one of the latest builds from main](https://github.com/UnitTestBot/UTBotJava/actions/runs/3180887399)
5. Open the generated test

**Expected behavior**

Information in Java docs is supposed to be correctly displayed in rendered mode.

**Actual behavior**

Java docs are displayed as one blank string in rendered mode.

**Visual proofs (screenshots, logs, images)**

image

image

**Environment**

WIndows 10 Pro
IntelliJ IDEA 2022.1.4

**Additional context**

Also reproducing in IDEA 2022.2.2 - with plugin from #1067 

Also applicable for UtUtils class methods Java docs:

image

image

_Originally posted by @alisevych in https://github.com/UnitTestBot/UTBotJava/issues/1068#issuecomment-1266751577_

### PR DESCRIPTION
**Pull request by onewhl**
# Description

Fixes #1078 

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Automated Testing

Specify tests that help to verify the change automatically.  

_Example:_ org.utbot.examples.algorithms.BinarySearchTest

## Manual Scenario 

Please, provide several scenarios that you went through to verify that the change worked as expected.  

# Checklist (remove irrelevant options):

- [ ] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [ ] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [ ] No new warnings
- [ ] New tests have been added
- [ ] All tests pass locally with my changes

### CODE REVIEW

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtDocumentationProvider.kt [hunk 1]
```diff
@@ -37,14 +37,20 @@ class UtDocumentationProvider : JavaDocumentationProvider() {
         docComment: PsiDocComment,
         comment: PsiDocCommentBase
     ): String? {
-        // add UTBot sections with custom tags.
         val utJavaDocInfoGenerator = UtJavaDocInfoGenerator()
-        return if (baseJavaDocInfo != null && baseJavaDocInfo.contains("utbot")) {
+        // case 1: IDE successfully parsed comment with plugin's custom tags,
```
Comment (amandelpie) [inline utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtDocumentationProvider.kt:41]: could we add to the comments some info about IDE versions leading to different branches?

**Review by amandelpie — APPROVED** [review]

File: utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtDocumentationProvider.kt (hunk 1 above)
Comment (onewhl) [reply utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtDocumentationProvider.kt]: done!
