### PR TITLE
Go. Bug fixes

### LINKED ISSUE #2044: Go. Empty test file is generated in a new Go project
**Description**

Empty test file is generated for `samples.go`

**To Reproduce**

1. Open IntelliJ Idea 2022.3 Ultimate
2. Install [plugin built from unit-test-bot/rc2023.3 branch](https://github.com/UnitTestBot/UTBotJava/actions/runs/4487896210)
3. Create a new Go project 
4. Copy-paste `utbot-go/go-samples/simple` folder into it
5. Turn 'Experimental languages support' on
6. Use plugin to generate tests for any/all of the functions in `samples.go`

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

Empty test file is generated.

**Visual proofs (screenshots, logs, images)**

~~~go
package simple

~~~

**Environment**

Windows 10 Pro
IntelliJ Idea 2022.3 Ultimate
Go 1.20.1

**Additional context**

In UTBotJava project tests are generated.

[Mar24Go.zip](https://github.com/UnitTestBot/UTBotJava/files/11063666/Mar24Go.zip)

### LINKED ISSUE #2045: Go. KlaxonException in IDEA 2022.2.4
**Description**

_Example:_ There are hundreds of error messages in the UTBot log. Looks like the problem is in the concrete executor.

**To Reproduce**

1. Open IntelliJ Idea 2022.3 Ultimate
2. Install [release 2022.12.1 plugin](https://github.com/UnitTestBot/UTBotJava/releases/tag/2022.12.1)
3. Create a new Go project 
4. Copy-paste `supported_types.go` into it
5. Turn 'Experimental languages support' on
6. Use plugin to generate tests for the samples

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

KlaxonException is thrown in IDEA

**Visual proofs (screenshots, logs, images)**

~~~java
com.beust.klaxon.KlaxonException: Unable to instantiate AnalyzedStructType:No argument provided for a required parameter: parameter #1 packageName of fun `<init>`(kotlin.String, kotlin.String, kotlin.String, kotlin.Boolean, kotlin.collections.List<org.utbot.go.gocodeanalyzer.AnalyzedStructType.AnalyzedField>): org.utbot.go.gocodeanalyzer.AnalyzedStructType
No argument provided for a required parameter: parameter #1 packageName of fun `<init>`(kotlin.String, kotlin.String, kotlin.String, kotlin.Boolean, kotlin.collections.List<org.utbot.go.gocodeanalyzer.AnalyzedStructType.AnalyzedField>): org.utbot.go.gocodeanalyzer.AnalyzedStructType
No argument provided for a required parameter: parameter #1 packageName of fun `<init>`(kotlin.String, kotlin.String, kotlin.String, kotlin.Boolean, kotlin.collections.List<org.utbot.go.gocodeanalyzer.AnalyzedStructType.AnalyzedField>): org.utbot.go.gocodeanalyzer.AnalyzedStructType
No argument provided for a required parameter: parameter #1 packageName of fun `<init>`(kotlin.String, kotlin.String, kotlin.String, kotlin.Boolean, kotlin.collections.List<org.utbot.go.gocodeanalyzer.AnalyzedStructType.AnalyzedField>): org.utbot.go.gocodeanalyzer.AnalyzedStructType

	at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:115)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:30)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:223)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:40)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:207)
	at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:66)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:30)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:223)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:40)
	at com.beust.klaxon.DefaultConverter.fromCollection(DefaultConverter.kt:141)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:39)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:207)
	at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:66)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:30)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:223)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:40)
	at com.beust.klaxon.DefaultConverter.fromCollection(DefaultConverter.kt:141)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:39)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:207)
	at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:66)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:30)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:223)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:40)
	at com.beust.klaxon.DefaultConverter.fromCollection(DefaultConverter.kt:141)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:39)
	at com.beust.klaxon.JsonObjectConverter.retrieveKeyValues(JsonObjectConverter.kt:207)
	at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:66)
	at com.beust.klaxon.JsonObjectConverter.fromJson(JsonObjectConverter.kt:30)
	at com.beust.klaxon.DefaultConverter.fromJsonObject(DefaultConverter.kt:223)
	at com.beust.klaxon.DefaultConverter.fromJson(DefaultConverter.kt:40)
	at com.beust.klaxon.Klaxon.fromJsonObject(Klaxon.kt:296)
	at org.utbot.go.gocodeanalyzer.GoSourceCodeAnalyzer.analyzeGoSourceFilesForFunctions(GoSourceCodeAnalyzer.kt:168)
	at org.utbot.go.logic.AbstractGoUtTestsGenerationController.generateTests(AbstractGoUtTestsGenerationController.kt:17)
	at org.utbot.intellij.plugin.language.go.generator.GoUtTestsDialogProcessor$createTests$1.run(GoUtTestsDialogProcessor.kt:91)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
~~~

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.2.4 Ultimate
Go 1.20.1

### PR DESCRIPTION
**Pull request by egiptipavel**
## Description

* Fixed bug with embedded unexported structs
* Removed timeout for worker execution
* Added logging when worker doesn't finish
* Fixes #2044 
* Fixes #2045 

### Manual tests

Test on `utbot-go/go-samples/simple/samples.go` and `utbot-go/go-samples/simple/supported_types.go` files.

## Self-check list

Check off the item if the statement is true. Hint: [x] is a marked item.

Please do not delete the list or its items.

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

### CODE REVIEW

File: utbot-go/src/main/kotlin/org/utbot/go/logic/GoTestCasesGenerator.kt [hunk 1]
```diff
@@ -112,7 +112,13 @@ object GoTestCasesGenerator {
                     val processHasExited = process.waitFor(endOfWorkerExecutionTimeout, TimeUnit.MILLISECONDS)
                     if (!processHasExited) {
                         process.destroy()
-                        throw TimeoutException("Timeout exceeded: Worker didn't finish")
+                        val processOutput = InputStreamReader(process.inputStream).readText()
+                        throw TimeoutException(
+                            StringBuilder()
```
Comment (Markoutte) [inline utbot-go/src/main/kotlin/org/utbot/go/logic/GoTestCasesGenerator.kt:117]: You can use `buildString {  }` to do the same

File: utbot-go/src/main/kotlin/org/utbot/go/logic/GoTestCasesGenerator.kt [hunk 2]
```diff
@@ -112,7 +112,13 @@ object GoTestCasesGenerator {
                     val processHasExited = process.waitFor(endOfWorkerExecutionTimeout, TimeUnit.MILLISECONDS)
                     if (!processHasExited) {
                         process.destroy()
-                        throw TimeoutException("Timeout exceeded: Worker didn't finish")
+                        val processOutput = InputStreamReader(process.inputStream).readText()
```
Comment (Markoutte) [inline utbot-go/src/main/kotlin/org/utbot/go/logic/GoTestCasesGenerator.kt:115]: Output can be huge. Do this read really necessary?

File: utbot-go/src/main/kotlin/org/utbot/go/logic/GoTestCasesGenerator.kt [hunk 3]
```diff
@@ -132,7 +138,13 @@ object GoTestCasesGenerator {
                     val processHasExited = process.waitFor(endOfWorkerExecutionTimeout, TimeUnit.MILLISECONDS)
                     if (!processHasExited) {
                         process.destroy()
-                        logger.error { "Timeout exceeded: Worker didn't finish" }
+                        val processOutput = InputStreamReader(process.inputStream).readText()
```
Comment (Markoutte) [inline utbot-go/src/main/kotlin/org/utbot/go/logic/GoTestCasesGenerator.kt:141]: Same comments as before

**Review by Markoutte — APPROVED** [review]

**Review by Markoutte — APPROVED** [review]
