### PR TITLE
`UtAssembleModel` refactor #812

### LINKED ISSUE #812: StackOverflow when constructing an object with Assemble Model
**Description**

When trying to generate tests for a method that returns an object with cross-reference relationship, *StackOverflow* exception is thrown.

**To Reproduce**

1. Generate a test for the following code:

```java
class FirstClass {
    SecondClass secondClass;

    FirstClass(SecondClass second) {
        this.secondClass = second;
    }
}

class SecondClass {
    FirstClass firstClass;

    SecondClass(FirstClass first) {
        this.firstClass = first;
    }
}

public class ClassWithCrossReferenceRelationship {
    public FirstClass returnFirstClass(int value) {
        if (value == 0) {
            return new FirstClass(new SecondClass(null));
        } else {
            FirstClass first = new FirstClass(null);
            first.secondClass = new SecondClass(first);

            return first;
        }
    }
}
```

**Actual behavior**

```
java.lang.StackOverflowError
	at java.base/java.util.ArrayList.addAll(ArrayList.java:702)
	at kotlin.collections.CollectionsKt___CollectionsKt.plus(_Collections.kt:3270)
	at org.utbot.framework.plugin.api.UtAssembleModel.getAllStatementsChain(Api.kt:504)
	at org.utbot.engine.ValueConstructor.constructFromAssembleModel(ValueConstructor.kt:327)
	at org.utbot.engine.ValueConstructor.construct(ValueConstructor.kt:190)
	at org.utbot.engine.ValueConstructor.value(ValueConstructor.kt:405)
	at org.utbot.engine.ValueConstructor.updateWithExecutableCallModel(ValueConstructor.kt:347)
	at org.utbot.engine.ValueConstructor.constructFromAssembleModel(ValueConstructor.kt:329)
	at org.utbot.engine.ValueConstructor.construct(ValueConstructor.kt:190)
	at org.utbot.engine.ValueConstructor.value(ValueConstructor.kt:405)
	at org.utbot.engine.ValueConstructor.updateWithExecutableCallModel(ValueConstructor.kt:347)
	at org.utbot.engine.ValueConstructor.constructFromAssembleModel(ValueConstructor.kt:329)
	at org.utbot.engine.ValueConstructor.construct(ValueConstructor.kt:190)
	at org.utbot.engine.ValueConstructor.value(ValueConstructor.kt:405)
	...
	...
```

**Additional context**

Setting `useAssembleModelGenerator` to *false* bypasses the problem.
However, it leads to *NoSuchFieldException*.
```
.
+-- JUnit Jupiter [OK]
| '-- ClassWithCrossReferenceRelationshipGeneratedTest [OK]
|   +-- returnFirstClass: value == 0 : True -> return new FirstClass(new SecondClass(nul... [X] modifiers
|   '-- returnFirstClass: value == 0 : False -> return first [OK]
+-- JUnit Vintage [OK]
'-- JUnit Platform Suite [OK]

Failures (1):
  JUnit Jupiter:ClassWithCrossReferenceRelationshipGeneratedTest:returnFirstClass: value == 0 : True -> return new FirstClass(new SecondClass(null))
    MethodSource [className = 'org.utbot.examples.codegen.deepequals.ClassWithCrossReferenceRelationshipGeneratedTest', methodName = 'testReturnFirstClass_ValueEqualsZero', methodParameterTypes = '']
    => java.lang.NoSuchFieldException: modifiers
       java.base/java.lang.Class.getDeclaredField(Class.java:2610)
       org.utbot.examples.codegen.deepequals.ClassWithCrossReferenceRelationshipGeneratedTest.setField(ClassWithCrossReferenceRelationshipGeneratedTest.java:312)
       org.utbot.examples.codegen.deepequals.ClassWithCrossReferenceRelationshipGeneratedTest.testReturnFirstClass_ValueEqualsZero(ClassWithCrossReferenceRelationshipGeneratedTest.java:67)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
       java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.base/java.lang.reflect.Method.invoke(Method.java:568)
       org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
       org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
       org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
       [...]
```

### PR DESCRIPTION
**Pull request by sergeypospelov**
# Description

Refactored API:
- Removed useless `UtExecutableCallModel::returnValue`. It was providing duplicate information accordingly to our use cases. Rewrote these use cases, with relying on another API.
- Changed `UtAssembleModel::instantiationChain` to `UtAssembleModel::instantiationCall`
- Made the primary constructor of `UtAssembleModel` private due to its unclear syntax with mutable lists. Added a more understandable (in my point of view) constructor. Rewrote all the usages of the previous one.
- Updated in-code documentation.
- Fixed an error in the `AssembleModelGenerator` and turned on a test, which checks this error.

Fixes #812

## Type of Change

- Bug fix (non-breaking change which fixes an issue)
- Refactoring (typos and non-functional changes) 

# How Has This Been Tested?

## Automated Testing

Turned on `org.utbot.examples.codegen.deepequals.ClassWithCrossReferenceRelationshipTest`

# Checklist:

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [x] New tests have been added
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-framework/src/main/kotlin/org/utbot/framework/concrete/IterableConstructors.kt [hunk 1]
```diff
@@ -1,68 +1,72 @@
...
-        modificationChain: MutableList<UtStatementModel>,
-        valueToConstructFrom: Any
-    ) {
+        value: Any
+    ): List<UtStatementModel> {
         @Suppress("PLATFORM_CLASS_MAPPED_TO_KOTLIN")
-        valueToConstructFrom as java.util.Collection<*>
+        value as java.util.Collection<*>
 
         // If [valueToConstructFrom] constructed incorrectly (some inner transient fields are null, etc.) this may fail.
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/framework/concrete/IterableConstructors.kt:22]: Not `valueToConstructFrom` anymore but just `value`

File: utbot-framework/src/main/kotlin/org/utbot/framework/assemble/AssembleModelGenerator.kt [hunk 2]
```diff
@@ -289,28 +284,39 @@ class AssembleModelGenerator(private val methodPackageName: String) {
...
-        return modelBefore.copy(
-            instantiationChain = instantiationChain,
-            modificationsChain = modificationChain,
+        return UtAssembleModel(
+            modelBefore.id,
+            modelBefore.classId,
+            modelBefore.modelName,
+            assembleExecutableCallModel(modelBefore.instantiationCall),
+            modelBefore.origin
         ).apply {
```
Comment (Damtev) [inline utbot-framework/src/main/kotlin/org/utbot/framework/assemble/AssembleModelGenerator.kt:294]: Looks like we should not have this `apply` anymore

**Review by Damtev — CHANGES_REQUESTED** [review]

File: utbot-framework/src/main/kotlin/org/utbot/engine/ValueConstructor.kt [hunk 3]
```diff
@@ -330,15 +328,21 @@ class ValueConstructor {
     private fun constructFromAssembleModel(assembleModel: UtAssembleModel): Any {
         constructedObjects[assembleModel]?.let { return it }
 
-        assembleModel.allStatementsChain.forEach { statementModel ->
+        val instantiationExecutableCall = assembleModel.instantiationCall
+        val result = updateWithExecutableCallModel(instantiationExecutableCall)
+        checkNotNull(result) {
+            "Tracked instance can't be null for call ${instantiationExecutableCall.executable} in model $assembleModel"
```
[the remark this answers is not in the document]
Comment (sergeypospelov) [reply utbot-framework/src/main/kotlin/org/utbot/engine/ValueConstructor.kt:334]: Done

File: utbot-framework/src/main/kotlin/org/utbot/framework/assemble/AssembleModelGenerator.kt (hunk 2 above)
Comment (sergeypospelov) [reply utbot-framework/src/main/kotlin/org/utbot/framework/assemble/AssembleModelGenerator.kt]: You are right, thank you

File: utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt [hunk 4]
```diff
@@ -200,50 +201,63 @@ internal class CgVariableConstructor(val context: CgContext) :
...
+        val cgCall = createCgExecutableCallFromUtExecutableCall(executableCall)
+
+        val type = when (executable) {
+            is MethodId -> executable.returnType
+            is ConstructorId -> executable.classId
+        }
+        // Don't use redundant constructors for primitives and String
+        val initExpr = if (isPrimitiveWrapperOrString(type)) cgLiteralForWrapper(params) else cgCall
+        newVar(type, model, baseName) { initExpr }
+            .takeIf { executableCall == model.instantiationCall }
```
Comment (SBOne-Kenobi) [inline utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt:239]: This statement is unnecessary

File: utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt [hunk 5]
```diff
@@ -200,50 +201,63 @@ internal class CgVariableConstructor(val context: CgContext) :
...
+        val executable = executableCall.executable
+        val params = executableCall.params
+        val cgCall = createCgExecutableCallFromUtExecutableCall(executableCall)
+
+        val type = when (executable) {
+            is MethodId -> executable.returnType
+            is ConstructorId -> executable.classId
+        }
+        // Don't use redundant constructors for primitives and String
+        val initExpr = if (isPrimitiveWrapperOrString(type)) cgLiteralForWrapper(params) else cgCall
```
Comment (SBOne-Kenobi) [inline utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt:237]: Move cgCall creation here

File: utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/objects/AssembleModelUtils.kt [hunk 6]
```diff
@@ -10,16 +10,13 @@ import org.utbot.fuzzer.hex
 
 
 fun ModelProvider.assembleModel(id: Int, constructorId: ConstructorId, params: List<FuzzedValue>): FuzzedValue {
-    val instantiationChain = mutableListOf<UtStatementModel>()
+    mutableListOf<UtStatementModel>()
```
Comment (SBOne-Kenobi) [inline utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/objects/AssembleModelUtils.kt:13]: Remove

**Review by SBOne-Kenobi — CHANGES_REQUESTED** [review]

File: utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt (hunk 4 above)
Comment (sergeypospelov) [reply utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgVariableConstructor.kt:239]: Thank you

**Review by SBOne-Kenobi — APPROVED** [review]
LGTM

**Review by Damtev — APPROVED** [review]
LGTM
