### PR TITLE
If utBotGenerationTimeoutInMillis value is out of allowed scope, Ille…

### LINKED ISSUE #1438: If `utBotGenerationTimeoutInMillis` value is out of allowed scope, IllegalArgumentException is thrown down to IDEA
**Description**

If timeout value is out of allowed scope, IllegalArgumentException is thrown down to IDEA.

**To Reproduce**

1. Install one of the latest plugin's builds from main, [build used](https://github.com/UnitTestBot/UTBotJava/actions/runs/3571922719)
2. Add the following line to `settings.properties`:

`utBotGenerationTimeoutInMillis=100`

3. Restart IDEA
4. Try to open UnitTestBot action dialog

**Expected behavior**

UnitTestBot action dialog with minimum allowed value - 1 sec - should be opened.

**Actual behavior**

Exception from UnitTestBot plugin is thrown down to IDEA:
```java
java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
...
at org.utbot.intellij.plugin.ui.GenerateTestsDialogWindow.<init>(GenerateTestsDialogWindow.kt:180)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor.createDialog(UtTestsDialogProcessor.kt:118)
```

**Visual proofs (screenshots, logs, images)**

~~~java
java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at java.desktop/javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:139)
	at java.desktop/javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:161)
	at com.intellij.ui.JBIntSpinner.<init>(JBIntSpinner.java:23)
	at org.utbot.intellij.plugin.ui.GenerateTestsDialogWindow.<init>(GenerateTestsDialogWindow.kt:180)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor.createDialog(UtTestsDialogProcessor.kt:118)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor.createDialogAndGenerateTests(UtTestsDialogProcessor.kt:82)
	at org.utbot.intellij.plugin.language.JvmLanguageAssistant.actionPerformed(JavaLanguage.kt:41)
	at org.utbot.intellij.plugin.ui.actions.GenerateTestsAction.actionPerformed(GenerateTestsAction.kt:9)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:717)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:717)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:714)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:658)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$5(IdeKeyEventDispatcher.java:669)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:84)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:16)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:78)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:16)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$6(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
~~~

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.2.3

### PR DESCRIPTION
**Pull request by Vassiliy-Kudryashov**
…galArgumentException is thrown down to IDEA #1438

Implement API for ranges for settings properties

# Description

API for properties validation was implemented, several numeric ranges were specified for UtSettings

Fixes #1438

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Manual Scenario 

See the issue:
1) Specify utBotGenerationTimeoutInMillis=100 in settings.properties
2) Start IDEA with the plugin and try to generate tests
Expected behavior: min value (1000) should be used instead of throwing Exception

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] No new warnings

### CODE REVIEW

File: utbot-core/src/main/kotlin/org/utbot/common/AbstractSettings.kt [hunk 1]
```diff
@@ -73,19 +78,25 @@ class PropertiesSettingsContainer(
...
+                            parsedValue = maxOf(parsedValue, range.first, range.third)
+                            parsedValue = minOf(parsedValue, range.second, range.third)
+                        }
                         customized = customized or (parsedValue != defaultValue)
                         return@SettingDelegate parsedValue
                     }
                     defaultValue
                 } catch (e: Throwable) {
-                    logger.info(e) { e.message }
+                    logger.warn("Cannot parse value for ${property.name}, default valu[$defaultValue] will be used instead") { e }
```
Comment (Markoutte) [inline utbot-core/src/main/kotlin/org/utbot/common/AbstractSettings.kt:99]: typo `valu[$defaultValue]`

**Review by Markoutte — APPROVED** [review]
