### PR TITLE
Fixed copyOf, copyOfRange and asList failures

### LINKED ISSUE #1699: `ClassNotFoundException` for `UtLinkedList`
**Description**

Contest Estimator fails on some classes because unable to find `UtLinkedList`.

**To Reproduce**

JDK8, Contest Estimator, project `fast-json-1.2.50`

**Expected behavior**

Clear Contest estimator log

**Actual behavior**

```
14:09:27.257 | ERROR | Internal job error
kotlinx.coroutines.JobCancellationException: StandaloneCoroutine is cancelling
Caused by: java.lang.ClassNotFoundException: org.utbot.engine.overrides.collections.UtLinkedList
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_352]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_352]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_352]
	at org.utbot.framework.plugin.api.util.IdUtilKt.getJClass(IdUtil.kt:101) ~[main/:?]
	at org.utbot.framework.plugin.api.ClassId.isAnonymous(Api.kt:815) ~[main/:?]
	at org.utbot.framework.assemble.AssembleModelGenerator.assembleModel(AssembleModelGenerator.kt:179) ~[main/:?]
	at org.utbot.framework.assemble.AssembleModelGenerator.createAssembleModels(AssembleModelGenerator.kt:112) ~[main/:?]
	at org.utbot.framework.assemble.AssembleModelGenerator.createAssembleModels(AssembleModelGenerator.kt:95) ~[main/:?]
	at org.utbot.engine.Resolver.resolveModels$utbot_framework(Resolver.kt:230) ~[main/:?]
	at org.utbot.engine.UtBotSymbolicEngine$traverseImpl$1.invokeSuspend(UtBotSymbolicEngine.kt:245) ~[main/:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.7.20.jar:1.7.20-release-201(1.7.20)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.6.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_352]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_352]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
```

### PR DESCRIPTION
**Pull request by Damtev**
# Description

Since real implementations of `Arrays.copyOf` and `Arrays.copyOfRange` are pretty difficult (due to reflection usage) for the symbolic engine, symbolic implementations are added in this PR. Also, since the mock implementation of `Arrays.asList` returns an instance of our class `UtArrayList`, some wrap hacks were added to prevent its appearance as a result of execution.

Fixes #1699 .

## Type of Change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

## Automated Testing

`org.utbot.examples.arrays.CopyOfExampleTest` and `org.utbot.examples.collections.ListsPart3Test#testAsListExample`

## Manual Scenario 

`org.antlr.v4.codegen.model.Recognizer.translateTokenStringsToTarget` in Contest Estimator.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings
- [x] New tests have been added

### CODE REVIEW

File: utbot-framework/src/main/java/org/utbot/engine/overrides/stream/Arrays.java [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package org.utbot.engine.overrides.stream;
 
 import org.utbot.api.annotation.UtClassMock;
+import org.utbot.api.mock.UtMock;
```
Comment (CaelmBleidd) [inline utbot-framework/src/main/java/org/utbot/engine/overrides/stream/Arrays.java:4]: Redundant?

File: utbot-framework/src/main/kotlin/org/utbot/engine/ObjectWrappers.kt [hunk 2]
```diff
@@ -236,8 +243,50 @@ private val wrappers = mapOf(
...
+        wrap(UtOptionalDouble::class) { _, addr -> objectValue(OPTIONAL_DOUBLE_TYPE, addr, OptionalWrapper(UT_OPTIONAL_DOUBLE)) },
+
+        wrap(UtThread::class) { _, addr -> objectValue(THREAD_TYPE, addr, ThreadWrapper()) },
+        wrap(UtThreadGroup::class) { _, addr -> objectValue(THREAD_GROUP_TYPE, addr, ThreadGroupWrapper()) },
+        wrap(UtExecutorService::class) { _, addr -> objectValue(EXECUTOR_SERVICE_TYPE, addr, ExecutorServiceWrapper()) },
+        wrap(UtCountDownLatch::class) { _, addr -> objectValue(COUNT_DOWN_LATCH_TYPE, addr, CountDownLatchWrapper()) },
+        wrap(UtCompletableFuture::class) { _, addr -> objectValue(COMPLETABLE_FUTURE_TYPE, addr, CompletableFutureWrapper()) },
+
+        wrap(UtArrayList::class) { _, addr -> objectValue(LIST_TYPE, addr, ListWrapper(UT_ARRAY_LIST)) },
+        wrap(UtLinkedList::class) { _, addr -> objectValue(LIST_TYPE, addr, ListWrapper(UT_LINKED_LIST)) },
```
Comment (CaelmBleidd) [inline utbot-framework/src/main/kotlin/org/utbot/engine/ObjectWrappers.kt:266]: Why are they have a list type here? In the wrappers above (e.g. UtStringBuilder and UtStringBuffer) you use concrete types instead of a common interface. Why?

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 3]
```diff
@@ -3216,6 +3225,69 @@ class Traverser(
...
+        implicitlyThrowException(NegativeArraySizeException("Length is less than zero"), setOf(isNegativeLength))
+        queuedSymbolicStateUpdates += mkNot(isNegativeLength).asHardConstraint()
+
+        val arrayType = src.type
+        val newArray = createNewArray(length, arrayType, arrayType.elementType)
+
+        return MethodResult(
+            newArray,
+            memoryUpdates = arrayUpdateWithValue(newArray.addr, arrayType, selectArrayExpressionFromMemory(src))
+        )
```
Comment (CaelmBleidd) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:3242]: I don't get it. You just created a new array with all unbounded variables. Why is it a copy of the original one? Or you copied the whole original massive even though it might be bigger than a copy? If it is so, please, provide a corresponding comment here

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 4]
```diff
@@ -3216,6 +3225,69 @@ class Traverser(
...
+    }
+
+    private fun TraversalContext.copyOfRange(parameters: List<SymbolicValue>): MethodResult {
+        val original = parameters[0] as ArrayValue
+        val from = parameters[1] as PrimitiveValue
+        val to = parameters[2] as PrimitiveValue
+
+        val originalLength = memory.findArrayLength(original.addr)
+
```
Comment (CaelmBleidd) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:3251]: Seems like a missed NPE check

File: utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt [hunk 5]
```diff
@@ -3216,6 +3225,69 @@ class Traverser(
...
+        val isFromBiggerThanLength = Gt(from, originalLength)
+        implicitlyThrowException(ArrayIndexOutOfBoundsException("From is bigger than original length"), setOf(isFromBiggerThanLength))
+        queuedSymbolicStateUpdates += mkNot(isFromBiggerThanLength).asHardConstraint()
+
+        val isFromBiggerThanTo = Gt(from, to)
+        implicitlyThrowException(IllegalArgumentException("From is bigger than to"), setOf(isFromBiggerThanTo))
+        queuedSymbolicStateUpdates += mkNot(isFromBiggerThanTo).asHardConstraint()
+
+        val newLength = Sub(to, from)
+        val newLengthValue = PrimitiveValue(IntType.v(), newLength)
```
Comment (CaelmBleidd) [inline utbot-framework/src/main/kotlin/org/utbot/engine/Traverser.kt:3265]: `newLength.toIntValue()`

File: utbot-framework/src/main/kotlin/org/utbot/engine/types/TypeResolver.kt [hunk 6]
```diff
@@ -349,11 +350,25 @@ internal val CLASS_REF_NUM_DIMENSIONS_DESCRIPTOR: MemoryChunkDescriptor
 
 internal val CLASS_REF_SOOT_CLASS: SootClass
     get() = Scene.v().getSootClass(CLASS_REF_CLASSNAME)
+internal val ARRAYS_SOOT_CLASS: SootClass
+    get() = Scene.v().getSootClass("java.util.Arrays")
```
Comment (CaelmBleidd) [inline utbot-framework/src/main/kotlin/org/utbot/engine/types/TypeResolver.kt:354]: Please, use a java class and its name for consistency with the code below

**Review by CaelmBleidd — CHANGES_REQUESTED** [review]

**Review by CaelmBleidd — APPROVED** [review]
