### PR TITLE
Go. Fix tests generation for functions with infinity loop 

### LINKED ISSUE #1802: Go. UTBot freezes when there is an infinite loop in a function
**Description**

UTBot freezes when there is an infinite loop in a function and then fails.

**To Reproduce**

1. Write the following function:
```Go
func InfinityLoop(n int) {
	for {
	}
}
```
2. Use plugin to generate tests

**Expected behavior**

Similar to this file should be generated.
```Go
package simple

// InfinityLoop(9223372036854775807) exceeded 1000 ms timeout

```

**Actual behavior**

UTBot freezes.

**Environment**

There is no specific environment.

### PR DESCRIPTION
**Pull request by egiptipavel**
## Description

* Added maximum trace length (1024).
* Removed `__traces__` global variable - now I change function signature and add `__trace__` parameter to it.
* Refactored Go code.

Fixes #1802 

### Manual tests

```Go
func InfinityLoop(n int) {
	for {
	}
}
```

## Self-check list

Check off the item if the statement is true. Hint: [x] is a marked item.

Please do not delete the list or its items.

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

### CODE REVIEW

File: utbot-go/src/main/kotlin/org/utbot/go/gocodeanalyzer/GoSourceCodeAnalyzer.kt [hunk 1]
```diff
@@ -31,7 +31,7 @@ object GoSourceCodeAnalyzer {
     fun analyzeGoSourceFilesForFunctions(
         targetFunctionsNamesBySourceFiles: Map<String, List<String>>,
         goExecutableAbsolutePath: String
-    ): Pair<Map<GoUtFile, GoSourceFileAnalysisResult>, Int> {
+    ): Triple<Map<GoUtFile, GoSourceFileAnalysisResult>, Int, Int> {
```
Comment (Markoutte) [inline utbot-go/src/main/kotlin/org/utbot/go/gocodeanalyzer/GoSourceCodeAnalyzer.kt:34]: Sometimes it should be converted into a class.

**Review by Markoutte — APPROVED** [review]

**Review by Markoutte — APPROVED** [review]
