### PR TITLE
Go. Big update

### LINKED ISSUE #2117: Go. RuntimeException: `Execution of GoSourceCodeAnalyzer` thrown in IDEA
**Description**

Tests are not generated for samples.go

**To Reproduce**

1. Open IntelliJ Idea 2022.3 Ultimate
2. Install [release 2023.3 plugin](https://github.com/UnitTestBot/UTBotJava/releases/tag/2023.3)
3. Create a new Go project 
4. Copy-paste `samples.go` into it
5. Turn 'Experimental languages support' on
6. Use plugin to generate tests for the samples

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

RuntimeException: `Execution of GoSourceCodeAnalyzer` thrown in IDEA

**Visual proofs (screenshots, logs, images)**

~~~
java.lang.RuntimeException: Execution of GoSourceCodeAnalyzer for AnalysisTargets(targets=[AnalysisTarget(absoluteFilePath=C:/Users/paagi/Desktop/Mar24Go/simple/samples.go, targetFunctionsNames=[StringSearch])]) in child process failed with non-zero exit code = 1: 
# internal/goexperiment
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# internal/goarch
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# internal/race
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# internal/goos
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# internal/unsafeheader
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# unicode
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# unicode/utf8
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# encoding
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# math/bits
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# internal/itoa
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# internal/syscall/windows/sysdll
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# unicode/utf16
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# internal/goversion
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# internal/cpu
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# runtime/internal/atomic
compile: version "go1.19.4" does not match go tool version "go1.20.1"
# sync/atomic
compile: version "go1.19.4" does not match go tool version "go1.20.1"

	at org.utbot.go.util.ProcessExecutionUtilKt.executeCommandByNewProcessOrFail(ProcessExecutionUtil.kt:29)
	at org.utbot.go.util.ProcessExecutionUtilKt.executeCommandByNewProcessOrFail$default(ProcessExecutionUtil.kt:6)
	at org.utbot.go.gocodeanalyzer.GoSourceCodeAnalyzer.analyzeGoSourceFilesForFunctions(GoSourceCodeAnalyzer.kt:69)
	at org.utbot.go.logic.AbstractGoUtTestsGenerationController.generateTests(AbstractGoUtTestsGenerationController.kt:17)
	at org.utbot.intellij.plugin.language.go.generator.GoUtTestsDialogProcessor$createTests$1.run(GoUtTestsDialogProcessor.kt:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
~~~

**Environment**

Windows 11
IntelliJ Idea 2022.3 Ultimate
Go 1.20.1

### PR DESCRIPTION
**Pull request by egiptipavel**
## Description

Added support for new types:
* pointers
* channels, interfaces (as function parameters)

Changed test generation template

Added support for methods

Parallel fuzzing

Traces -> coverage

Fixes #2117 

### Manual tests

Test on `utbot-go/go-samples/simple/samples.go` and `utbot-go/go-samples/simple/supported_types.go` files.

## Self-check list

- [x] I've set the proper **labels** for my PR (at least, for category and component).
- [x] PR **title** and **description** are clear and intelligible.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas.
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [x] **Manual tests** have been provided optionally.
- [ ] The **documentation** for the functionality I've been working on is up-to-date.

### CODE REVIEW

File: utbot-intellij-go/src/main/kotlin/org/utbot/intellij/plugin/language/go/ui/GenerateGoTestsDialogWindow.kt [hunk 1]
```diff
@@ -48,26 +63,42 @@ class GenerateGoTestsDialogWindow(val model: GenerateGoTestsModel) : DialogWrapp
 
     override fun createCenterPanel(): JComponent {
         panel = panel {
-            row("Test source root: near to source files") {}
-            row("Generate test methods for:") {}
+            row("Timeout for all functions:") {
+                cell(allFunctionExecutionTimeoutSecondsSpinner)
+                cell(JBLabel("seconds"))
+            }
+            row("Number of fuzzing processes:") {
```
Comment (Markoutte) [inline utbot-intellij-go/src/main/kotlin/org/utbot/intellij/plugin/language/go/ui/GenerateGoTestsDialogWindow.kt:70]: Should a user know about this number?

**Review by Markoutte — APPROVED** [review]

File: utbot-intellij-go/src/main/kotlin/org/utbot/intellij/plugin/language/go/ui/GenerateGoTestsDialogWindow.kt (hunk 1 above)
Comment (egiptipavel) [reply utbot-intellij-go/src/main/kotlin/org/utbot/intellij/plugin/language/go/ui/GenerateGoTestsDialogWindow.kt:70]: I think this is important if he wants to run fuzzing instead of generating tests.

File: utbot-go/src/main/kotlin/org/utbot/go/util/ProcessExecutionUtil.kt [hunk 2]
```diff
@@ -6,7 +6,7 @@ import java.nio.file.Path
 
 fun modifyEnvironment(goExecutableAbsolutePath: Path, gopathAbsolutePath: Path): MutableMap<String, String> {
     val environment = System.getenv().toMutableMap().apply {
-        this["Path"] = goExecutableAbsolutePath.parent.toString() + File.pathSeparator + (this["Path"] ?: "")
+        this["Path"] = goExecutableAbsolutePath.resolve(File.pathSeparator).toString() + (this["Path"] ?: "")
```
Comment (Markoutte) [inline utbot-go/src/main/kotlin/org/utbot/go/util/ProcessExecutionUtil.kt:9]: Resolve should resolve a child element of the current path.

**Review by Markoutte — CHANGES_REQUESTED** [review]

**Review by Markoutte — APPROVED** [review]
