### PR TITLE
Fixed FileNotFoundExecption during JavaParser work

### LINKED ISSUE #1227: Summaries are not generated due to FileNotFoundException
**Description**

Summaries are not generated due to FileNotFoundException  thrown in the [SourceCodeParser.kt:45](https://github.com/UnitTestBot/UTBotJava/blob/main/utbot-summary/src/main/kotlin/org/utbot/summary/ast/SourceCodeParser.kt#L45)

The error message is the following: "C:\Users\<username>\.jdks\corretto-11.0.16.1\lib\src.zip!\java.base\java\lang\Math.java (??????? ?? ??????? ????? ????????? ????)"

Need to say that the Math.java file is exist as a Zip entry in the archive with sources mentioned above

**To Reproduce**

1. Run runIde Gradle task
2. Copy to the open project the mentioned below snippet of code
3. Use plugin to generate tests for DoubleFunctions::hypo method

```
public class DoubleFunctions {
    public double hypo(double a, double b) {
        return Math.sqrt(Math.pow(a, 2) + Math.pow(b, 2));
    }

    @SuppressWarnings("ManualMinMaxCalculation")
    public double max(double a, double b) {
        return a > b ? a : b;
    }

    public double circleSquare(double r) {
        if (r < 0 || Double.isNaN(r) || r > 10000) {
            throw new IllegalArgumentException();
        }
        double square = Math.PI * r * r;
        if (square > 777.85) {
            return square;
        } else {
            return 0;
        }
    }

    public int numberOfRootsInSquareFunction(double a, double b, double c) {

        double result = b * b - 4 * a * c;
        if (result > 0) {
            return 2;
        } else if (result == 0) {
            return 1;
        }
        return 0;
    }
}
```

**Expected behavior**

Tests with summaries should be generated.

**Actual behavior**

Tests are generated without summaries.

**Visual proofs (screenshots, logs, images)**

image

**Environment**

The Coretto jdk 11.0.16.1 is installed and used in both, initial and debug IDEs

### PR DESCRIPTION
**Pull request by amandelpie**
# Description

Fixes #1227 #1204 

The main problem was the following: JavaParser tries to parse ZipEntry in zip archive with JDK sources.
ZipEntry is not a file.

To filter this situation, we decided to ignore these zipped sources from the standard library. In reality, we ignored it before @Domonion changes in the #1151 PR. 

We extended our scope and failed when faced with these issues.

The proposed solution helps to avoid situation with parsing of non-existing files and also improves the logging for some edge situations.

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Manual Scenario 

One of scenarios is described also in the ticket #1204 

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] All tests pass locally with my changes

### CODE REVIEW

File: utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt [hunk 1]
```diff
@@ -395,10 +401,15 @@ private fun invokeDescriptions(testSet: UtMethodTestSet, searchDirectory: Path):
                 sootMethod.declaringClass.javaPackageName.replace(".", File.separator),
                 searchDirectory
             )
-            val ast = methodFile?.let {
-                SourceCodeParser(sootMethod, it).methodAST
+
+            if (methodFile != null && methodFile.exists()) {
```
Comment (denis-fokin) [inline utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt:405]: My personal preference is to use as few nulls as possible
